# ■ SQLAlchemyでデータベース作成

In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /Users/otsukashigeki/opt/anaconda3/lib/python3.8/site-packages (1.3.20)
Note: you may need to restart the kernel to use updated packages.

In [1]:
from sqlalchemy import create_engine
from sqlalchemy.orm import scoped_session, sessionmaker
from sqlalchemy.ext.declarative import declarative_base

In [2]:
import pandas as pd
import os

In [3]:
database_file = os.path.join(os.path.abspath(os.getcwd()), 'data.db')

In [4]:
database_file

'/Users/otsukashigeki/python/app_flask/data.db'

In [5]:
engine = create_engine('sqlite:///' + database_file, convert_unicode=True, echo=True)

In [6]:
from sqlalchemy import Column, Integer, Float, String

In [7]:
db_session = scoped_session(
    sessionmaker(
        autocommit = False,
        autoflush = False,
        bind = engine
    )
)

In [8]:
Base = declarative_base()
Base.query = db_session.query_property()

In [9]:
class WH(Base):
    __tablename__ = 'WH_class'
    id = Column(Integer, primary_key=True)
    WH_num = Column(Integer, unique=True)
    WH_name = Column(String)
    text = Column(String)
    
    def __init__(self, WH_num=None, WH_name=None, text=None):
        self.WH_num = WH_num
        self.WH_name = WH_name
        self.text = text

In [10]:
Base.metadata.create_all(bind=engine)

2022-05-02 17:46:54,526 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2022-05-02 17:46:54,527 INFO sqlalchemy.engine.base.Engine ()
2022-05-02 17:46:54,528 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2022-05-02 17:46:54,529 INFO sqlalchemy.engine.base.Engine ()
2022-05-02 17:46:54,530 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("WH_class")
2022-05-02 17:46:54,531 INFO sqlalchemy.engine.base.Engine ()
2022-05-02 17:46:54,532 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("WH_class")
2022-05-02 17:46:54,532 INFO sqlalchemy.engine.base.Engine ()
2022-05-02 17:46:54,534 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "WH_class" (
	id INTEGER NOT NULL,
	"WH_num" INTEGER,
	"WH_name" VARCHAR,
	text VARCHAR,
	PRIMARY KEY (id),
	UNIQUE ("WH_num")
)


2022-05-02 17:46:54,535 INFO sqlalchemy.engine.base.Engine ()
2022-05-02 17:46:54,537 INFO sqlalchemy.engine.base.Engine COMMIT

In [11]:
def read_data():
    WH_df = pd.read_csv('/Users/otsukashigeki/Desktop/WH_sql.csv')

    for index, _df in WH_df.iterrows():
        row = WH(WH_num=_df['Heritage_num'], WH_name=_df['Heritage_name'], text=_df['Text'])
        db_session.add(row)
    db_session.commit()

In [12]:
read_data()

2022-05-02 17:46:54,900 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2022-05-02 17:46:54,904 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,904 INFO sqlalchemy.engine.base.Engine (1, 'ヴァトナヨークトル国立公園：火山と氷河がつくるダイナミックな自然', nan)
2022-05-02 17:46:54,905 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,905 INFO sqlalchemy.engine.base.Engine (2, 'シングヴェトリル国立公園', nan)
2022-05-02 17:46:54,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,906 INFO sqlalchemy.engine.base.Engine (3, 'スルツェイ火山島', nan)
2022-05-02 17:46:54,906 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,906 INFO sqlalchemy.engine.base.Engine (4, 'スケリッグ・マイケル', nan)
2022-05-02 17:46:54,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,907 INFO sqlalchemy.engine.base.Engine (5, 'ブルー・ナ・ボーニャ：ボイン渓谷の考古遺跡群', nan)
2022-05-02 17:46:54,907 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,908 INFO sqlalchemy.engine.base.Engine (6, 'ゴブスタン・ロック・アートの文化的景観', nan)
2022-05-02 17:46:54,908 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,908 INFO sqlalchemy.engine.base.Engine (7, 'シルヴァンシャー宮殿と乙女の塔のある城壁都市バクー', nan)
2022-05-02 17:46:54,909 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,909 INFO sqlalchemy.engine.base.Engine (8, 'ハーンの宮殿のあるシェキの歴史地区 ', nan)
2022-05-02 17:46:54,910 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,910 INFO sqlalchemy.engine.base.Engine (9, 'ジャームのミナレットと考古遺跡群', nan)
2022-05-02 17:46:54,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,911 INFO sqlalchemy.engine.base.Engine (10, 'バーミヤン渓谷の文化的景観と古代遺跡群', nan)
2022-05-02 17:46:54,911 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,911 INFO sqlalchemy.engine.base.Engine (11, 'イエローストーン国立公園', nan)
2022-05-02 17:46:54,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,912 INFO sqlalchemy.engine.base.Engine (12, 'エヴァーグレーズ国立公園', nan)
2022-05-02 17:46:54,912 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,913 INFO sqlalchemy.engine.base.Engine (13, 'オリンピック国立公園', nan)
2022-05-02 17:46:54,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,913 INFO sqlalchemy.engine.base.Engine (14, 'カールズバッド洞窟群国立公園', nan)
2022-05-02 17:46:54,913 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,914 INFO sqlalchemy.engine.base.Engine (15, 'カホキア・マウンド州立史跡', nan)
2022-05-02 17:46:54,914 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,914 INFO sqlalchemy.engine.base.Engine (16, 'グランド・キャニオン国立公園', nan)
2022-05-02 17:46:54,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,915 INFO sqlalchemy.engine.base.Engine (17, 'グレート・スモーキー山脈国立公園', nan)
2022-05-02 17:46:54,915 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,915 INFO sqlalchemy.engine.base.Engine (18, 'シャーロットヴィルのモンティチェロとヴァージニア大学', nan)
2022-05-02 17:46:54,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,916 INFO sqlalchemy.engine.base.Engine (19, '自由の女神像', nan)
2022-05-02 17:46:54,916 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,916 INFO sqlalchemy.engine.base.Engine (20, 'タオス・プエブロの伝統的集落', nan)
2022-05-02 17:46:54,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,917 INFO sqlalchemy.engine.base.Engine (21, 'チャコ文化', nan)
2022-05-02 17:46:54,917 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,917 INFO sqlalchemy.engine.base.Engine (22, '独立記念館', nan)
2022-05-02 17:46:54,918 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,918 INFO sqlalchemy.engine.base.Engine (23, 'パパハナウモクアケア', nan)
2022-05-02 17:46:54,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,919 INFO sqlalchemy.engine.base.Engine (24, 'ハワイ火山国立公園', nan)
2022-05-02 17:46:54,919 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,920 INFO sqlalchemy.engine.base.Engine (25, 'プエルト・リコの要塞とサン・フアン国立歴史地区', nan)
2022-05-02 17:46:54,920 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,920 INFO sqlalchemy.engine.base.Engine (26, 'マンモス・ケーブ国立公園', nan)
2022-05-02 17:46:54,921 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,922 INFO sqlalchemy.engine.base.Engine (27, 'メサ・ヴェルデ国立公園', nan)
2022-05-02 17:46:54,923 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,924 INFO sqlalchemy.engine.base.Engine (28, 'ヨセミテ国立公園', nan)
2022-05-02 17:46:54,924 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,924 INFO sqlalchemy.engine.base.Engine (29, 'レッドウッド国立・州立公園群', nan)
2022-05-02 17:46:54,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,925 INFO sqlalchemy.engine.base.Engine (30, 'ポヴァティ・ポイントの記念碑的土塁群', nan)
2022-05-02 17:46:54,925 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,926 INFO sqlalchemy.engine.base.Engine (31, 'サン・アントニオ・ミッションズ', nan)
2022-05-02 17:46:54,926 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,926 INFO sqlalchemy.engine.base.Engine (32, 'フランク・ロイド・ライトの20世紀の建築', nan)
2022-05-02 17:46:54,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,927 INFO sqlalchemy.engine.base.Engine (33, 'ウォータートン・グレーシャー国際平和自然公園', nan)
2022-05-02 17:46:54,927 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,927 INFO sqlalchemy.engine.base.Engine (34, 'アラスカ・カナダ国境地帯の山岳国立公園群：クルアニ、ランゲル・セント・エライアス、グレイシャー・ベイ、タッシェンシニ・アルセク', nan)
2022-05-02 17:46:54,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,928 INFO sqlalchemy.engine.base.Engine (35, 'アル・アインの文化的遺跡群（ハフィート、ヒリ、ビダ・ビント・サウードとオアシス群）', nan)
2022-05-02 17:46:54,928 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,928 INFO sqlalchemy.engine.base.Engine (36, 'アルジェの旧市街カスバ', nan)
2022-05-02 17:46:54,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,929 INFO sqlalchemy.engine.base.Engine (37, 'ジェミーラの考古遺跡', nan)
2022-05-02 17:46:54,929 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:54,929 INFO sqlalchemy.engine.base.Engine (38, 'タッシリ・ナジェール', nan)
2022-05-02 17:46:54,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,930 INFO sqlalchemy.engine.base.Engine (39, 'ティパサの考古遺跡', nan)
2022-05-02 17:46:54,930 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,931 INFO sqlalchemy.engine.base.Engine (40, 'ティムガッドの考古遺跡', nan)
2022-05-02 17:46:54,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,931 INFO sqlalchemy.engine.base.Engine (41, 'ムザブの谷', nan)
2022-05-02 17:46:54,931 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,931 INFO sqlalchemy.engine.base.Engine (42, '城塞都市ベニー・ハンマード', nan)
2022-05-02 17:46:54,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,932 INFO sqlalchemy.engine.base.Engine (43, 'イグアス国立公園', nan)
2022-05-02 17:46:54,932 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,933 INFO sqlalchemy.engine.base.Engine (44, 'イスチグアラストとタランパヤ自然公園群', nan)
2022-05-02 17:46:54,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,933 INFO sqlalchemy.engine.base.Engine (45, 'ケブラーダ・デ・ウマウアカ', nan)
2022-05-02 17:46:54,933 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,934 INFO sqlalchemy.engine.base.Engine (46, 'コルドバのイエズス会管区教会堂と農園跡', nan)
2022-05-02 17:46:54,934 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,934 INFO sqlalchemy.engine.base.Engine (47, 'バルデス半島', nan)
2022-05-02 17:46:54,935 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,935 INFO sqlalchemy.engine.base.Engine (48, 'ピントゥラス川のクエバ・デ・ラス・マノス', nan)
2022-05-02 17:46:54,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,936 INFO sqlalchemy.engine.base.Engine (49, 'ロス・グラシアレス国立公園', nan)
2022-05-02 17:46:54,936 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,936 INFO sqlalchemy.engine.base.Engine (50, 'ロス・アレルセス国立公園', nan)
2022-05-02 17:46:54,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,937 INFO sqlalchemy.engine.base.Engine (51, 'グアラニのイエズス会布教施設群：サン・イグナシオ・ミニ、サンタ・アナ、ヌエストラ・セニョーラ・デ・ロレト、サンタ・マリア・マヨール（アルゼンチン側）、サン・ミゲル・ダス・ミソンイス（ブラジル側）', nan)
2022-05-02 17:46:54,937 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,937 INFO sqlalchemy.engine.base.Engine (52, 'カパック・ニャン：アンデスの道', nan)
2022-05-02 17:46:54,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,938 INFO sqlalchemy.engine.base.Engine (53, 'ブトリントの考古遺跡', nan)
2022-05-02 17:46:54,938 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,938 INFO sqlalchemy.engine.base.Engine (54, 'ベラトとギロカストラの歴史地区', nan)
2022-05-02 17:46:54,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,939 INFO sqlalchemy.engine.base.Engine (55, 'アフパットとサナインの修道院', nan)
2022-05-02 17:46:54,939 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,939 INFO sqlalchemy.engine.base.Engine (56, 'エチミアジンの大聖堂と教会群、およびズヴァルトノツの考古遺跡', nan)
2022-05-02 17:46:54,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,940 INFO sqlalchemy.engine.base.Engine (57, 'ゲガルト修道院とアザート渓谷上流域', nan)
2022-05-02 17:46:54,940 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,940 INFO sqlalchemy.engine.base.Engine (58, 'ンバンザ・コンゴ：旧コンゴ王国の首都の遺跡', nan)
2022-05-02 17:46:54,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,941 INFO sqlalchemy.engine.base.Engine (59, 'アンティグアの海軍造船所と関連考古遺跡群', nan)
2022-05-02 17:46:54,941 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,941 INFO sqlalchemy.engine.base.Engine (60, 'マドリウ・パラフィタ・クラロー渓谷', nan)
2022-05-02 17:46:54,942 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,942 INFO sqlalchemy.engine.base.Engine (61, 'サナアの旧市街', nan)
2022-05-02 17:46:54,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,943 INFO sqlalchemy.engine.base.Engine (62, 'ザビードの歴史地区', nan)
2022-05-02 17:46:54,943 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,944 INFO sqlalchemy.engine.base.Engine (63, '城壁都市シバーム', nan)
2022-05-02 17:46:54,944 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,945 INFO sqlalchemy.engine.base.Engine (64, 'ソコトラ諸島', nan)
2022-05-02 17:46:54,945 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,945 INFO sqlalchemy.engine.base.Engine (65, 'アッコの旧市街', nan)
2022-05-02 17:46:54,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,946 INFO sqlalchemy.engine.base.Engine (66, 'ネゲヴにある香料の道と砂漠都市群', nan)
2022-05-02 17:46:54,946 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,946 INFO sqlalchemy.engine.base.Engine (67, '聖書ゆかりの遺丘群：メギド、ハゾル、ベエル・シェバ', nan)
2022-05-02 17:46:54,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,947 INFO sqlalchemy.engine.base.Engine (68, 'テル・アビーブの近代都市ホワイト・シティ', nan)
2022-05-02 17:46:54,947 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,947 INFO sqlalchemy.engine.base.Engine (69, 'ハイファと西ガリラヤのバハイ教聖所群', nan)
2022-05-02 17:46:54,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,948 INFO sqlalchemy.engine.base.Engine (70, 'マサダ国立公園', nan)
2022-05-02 17:46:54,948 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,949 INFO sqlalchemy.engine.base.Engine (71, 'カルメル山の人類の進化を示す遺跡群：ナハル・メアロット／ワディ・エル・ムガラ洞窟', nan)
2022-05-02 17:46:54,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,949 INFO sqlalchemy.engine.base.Engine (72, 'ユダヤ低地にあるマレシャとベト・グヴリンの洞窟群：洞窟の大地の小宇宙', nan)
2022-05-02 17:46:54,949 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,950 INFO sqlalchemy.engine.base.Engine (73, 'ベート・シェアリムのネクロポリス：ユダヤ人再興の中心地', nan)
2022-05-02 17:46:54,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,950 INFO sqlalchemy.engine.base.Engine (74, 'アルプス山脈周辺の先史時代の掘立柱住居群', nan)
2022-05-02 17:46:54,950 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,951 INFO sqlalchemy.engine.base.Engine (75, 'アクィレイアの考古地区とバシリカ総主教聖堂', nan)
2022-05-02 17:46:54,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:54,951 INFO sqlalchemy.engine.base.Engine (76, 'アグリジェントの考古地区', nan)
2022-05-02 17:46:54,951 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,952 INFO sqlalchemy.engine.base.Engine (77, 'アッシジのサン・フランチェスコ聖堂と関連建造物群', nan)
2022-05-02 17:46:54,952 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,953 INFO sqlalchemy.engine.base.Engine (78, 'アマルフィ海岸', nan)
2022-05-02 17:46:54,953 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,953 INFO sqlalchemy.engine.base.Engine (79, 'アルベロベッロのトゥルッリ', nan)
2022-05-02 17:46:54,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,954 INFO sqlalchemy.engine.base.Engine (80, 'イタリアのロンゴバルド族：権勢の足跡（568－774年）', nan)
2022-05-02 17:46:54,954 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,955 INFO sqlalchemy.engine.base.Engine (81, 'ヴァルカモニカ（カモニカ渓谷の岩絵群）', nan)
2022-05-02 17:46:54,955 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,956 INFO sqlalchemy.engine.base.Engine (82, 'ヴァル・ディ・ノートの後期バロック様式の都市景観群（シチリア島南東部）', nan)
2022-05-02 17:46:54,956 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,956 INFO sqlalchemy.engine.base.Engine (83, 'ヴィチェンツァの市街とヴェネト地方のパッラーディオ様式の別荘群', nan)
2022-05-02 17:46:54,957 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,958 INFO sqlalchemy.engine.base.Engine (84, 'ヴィッラ・ロマーナ・デル・カサーレ（古代ローマの別荘群）', nan)
2022-05-02 17:46:54,958 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,959 INFO sqlalchemy.engine.base.Engine (85, 'ヴェネツィアとその潟', nan)
2022-05-02 17:46:54,959 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,959 INFO sqlalchemy.engine.base.Engine (86, 'ヴェローナの市街', nan)
2022-05-02 17:46:54,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,960 INFO sqlalchemy.engine.base.Engine (87, 'ウルビーノの歴史地区', nan)
2022-05-02 17:46:54,960 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,961 INFO sqlalchemy.engine.base.Engine (88, 'エオーリエ諸島', nan)
2022-05-02 17:46:54,961 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,961 INFO sqlalchemy.engine.base.Engine (89, 'オルチア渓谷', nan)
2022-05-02 17:46:54,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,962 INFO sqlalchemy.engine.base.Engine (90, 'カステル・デル・モンテ', nan)
2022-05-02 17:46:54,962 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,963 INFO sqlalchemy.engine.base.Engine (91, 'カゼルタの18世紀の王宮と庭園、ヴァンヴィテッリの水道橋、サン・レウチョの関連遺産', nan)
2022-05-02 17:46:54,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,963 INFO sqlalchemy.engine.base.Engine (92, 'クレスピ・ダッダの企業都市', nan)
2022-05-02 17:46:54,963 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,964 INFO sqlalchemy.engine.base.Engine (93, 'サン・ジミニャーノの歴史地区', nan)
2022-05-02 17:46:54,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,964 INFO sqlalchemy.engine.base.Engine (94, 'シエナの歴史地区', nan)
2022-05-02 17:46:54,964 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,965 INFO sqlalchemy.engine.base.Engine (95, 'ジェノヴァ：レ・ストラーデ・ヌオーヴェとパラッツィ・デイ・ロッリ制度', nan)
2022-05-02 17:46:54,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,965 INFO sqlalchemy.engine.base.Engine (96, 'シラクサとパンタリカの岩壁墓地遺跡', nan)
2022-05-02 17:46:54,965 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,966 INFO sqlalchemy.engine.base.Engine (97, 'チェルヴェテリとタルクィニアのエトルリア古代古墳群', nan)
2022-05-02 17:46:54,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,966 INFO sqlalchemy.engine.base.Engine (98, 'チレント・ディアノ渓谷国立公園及び遺跡群と修道院', nan)
2022-05-02 17:46:54,966 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,967 INFO sqlalchemy.engine.base.Engine (99, 'ティヴォリのエステ家別荘', nan)
2022-05-02 17:46:54,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,967 INFO sqlalchemy.engine.base.Engine (100, 'ティヴォリのハドリアヌス別荘', nan)
2022-05-02 17:46:54,967 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,968 INFO sqlalchemy.engine.base.Engine (101, 'トリノのサヴォイア家の王宮と邸宅', nan)
2022-05-02 17:46:54,968 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,969 INFO sqlalchemy.engine.base.Engine (102, 'ドロミテ山塊', nan)
2022-05-02 17:46:54,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,969 INFO sqlalchemy.engine.base.Engine (103, 'ナポリの歴史地区', nan)
2022-05-02 17:46:54,969 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,970 INFO sqlalchemy.engine.base.Engine (104, 'パドヴァの植物園（オルト・ボタニコ）', nan)
2022-05-02 17:46:54,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,970 INFO sqlalchemy.engine.base.Engine (105, 'バルーミニのスー・ヌラージ', nan)
2022-05-02 17:46:54,970 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,971 INFO sqlalchemy.engine.base.Engine (106, 'ピエモンテとロンバルディアのサクロ・モンテ群', nan)
2022-05-02 17:46:54,971 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,972 INFO sqlalchemy.engine.base.Engine (107, 'ピエンツァの歴史地区', nan)
2022-05-02 17:46:54,972 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,972 INFO sqlalchemy.engine.base.Engine (108, 'ピサのドゥオーモ広場', nan)
2022-05-02 17:46:54,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,973 INFO sqlalchemy.engine.base.Engine (109, 'フィレンツェの歴史地区', nan)
2022-05-02 17:46:54,973 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,973 INFO sqlalchemy.engine.base.Engine (110, 'ポルトヴェーネレ、チンクエ・テッレと小島群（パルマリア島、ティーノ島、ティネット島）', nan)
2022-05-02 17:46:54,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,974 INFO sqlalchemy.engine.base.Engine (111, 'ポンペイ、エルコラーノ、トッレ・アヌンツィアータの考古地区', nan)
2022-05-02 17:46:54,974 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,975 INFO sqlalchemy.engine.base.Engine (112, 'マテーラの洞窟住居サッシと岩窟教会公園', nan)
2022-05-02 17:46:54,975 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,975 INFO sqlalchemy.engine.base.Engine (113, 'マントヴァとサッビオネータ', nan)
2022-05-02 17:46:54,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:54,976 INFO sqlalchemy.engine.base.Engine (114, 'ミラノのサンタ・マリア・デッレ・グラーツィエ修道院とレオナルド・ダ・ヴィンチの『最後の晩餐』', nan)
2022-05-02 17:46:54,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,976 INFO sqlalchemy.engine.base.Engine (115, 'モデナ：大聖堂と市民の塔（トッレ・チヴィカ）、グランデ広場', nan)
2022-05-02 17:46:54,976 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,977 INFO sqlalchemy.engine.base.Engine (116, 'ラヴェンナの初期キリスト教建造物群', nan)
2022-05-02 17:46:54,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,977 INFO sqlalchemy.engine.base.Engine (117, 'ルネサンス都市フェッラーラとポー川のデルタ地帯', nan)
2022-05-02 17:46:54,977 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,978 INFO sqlalchemy.engine.base.Engine (118, 'エトナ山', nan)
2022-05-02 17:46:54,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,978 INFO sqlalchemy.engine.base.Engine (119, 'トスカーナのメディチ家の別荘と庭園', nan)
2022-05-02 17:46:54,978 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,979 INFO sqlalchemy.engine.base.Engine (120, 'ピエモンテのブドウ園の景観：ランゲ・ロエロとモンフェッラート', nan)
2022-05-02 17:46:54,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,979 INFO sqlalchemy.engine.base.Engine (121, 'パレルモのアラブ・ノルマン様式の建造物群と、チェファルとモンレアーレの大聖堂', nan)
2022-05-02 17:46:54,979 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,980 INFO sqlalchemy.engine.base.Engine (122, 'イヴレーア：20世紀の産業都市', nan)
2022-05-02 17:46:54,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,980 INFO sqlalchemy.engine.base.Engine (123, 'コネリアーノとヴァルドッビアーデネのプロセッコ栽培丘陵群 ', nan)
2022-05-02 17:46:54,980 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,981 INFO sqlalchemy.engine.base.Engine (124, 'パドヴァの14世紀のフレスコ画群', nan)
2022-05-02 17:46:54,981 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,981 INFO sqlalchemy.engine.base.Engine (125, 'ボローニャのポルティコ群', nan)
2022-05-02 17:46:54,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,982 INFO sqlalchemy.engine.base.Engine (126, 'ローマの歴史地区と教皇領、サン・パオロ・フォーリ・レ・ムーラ聖堂', nan)
2022-05-02 17:46:54,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,982 INFO sqlalchemy.engine.base.Engine (127, 'アルブラとベルニナの景観とレーティッシュ鉄道', nan)
2022-05-02 17:46:54,982 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,983 INFO sqlalchemy.engine.base.Engine (128, 'サン・ジョルジオ山', nan)
2022-05-02 17:46:54,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,983 INFO sqlalchemy.engine.base.Engine (129, 'アッシュル（カラット・シェルカット）', nan)
2022-05-02 17:46:54,983 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,984 INFO sqlalchemy.engine.base.Engine (130, '円形都市ハトラ', nan)
2022-05-02 17:46:54,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,984 INFO sqlalchemy.engine.base.Engine (131, '古代都市サーマッラー', nan)
2022-05-02 17:46:54,984 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,985 INFO sqlalchemy.engine.base.Engine (132, 'エルビル城砦', nan)
2022-05-02 17:46:54,985 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,986 INFO sqlalchemy.engine.base.Engine (133, 'イラク南部のアフワル：生物多様性の保護地域とメソポタミアの都市の残存景観', nan)
2022-05-02 17:46:54,986 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,986 INFO sqlalchemy.engine.base.Engine (134, 'バビロン', nan)
2022-05-02 17:46:54,987 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,987 INFO sqlalchemy.engine.base.Engine (135, 'アルダビールのシャイフ・サフィ・アッディーン廟と関連建造物群', nan)
2022-05-02 17:46:54,988 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,988 INFO sqlalchemy.engine.base.Engine (136, 'イスファハーンのイマーム広場', nan)
2022-05-02 17:46:54,989 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,989 INFO sqlalchemy.engine.base.Engine (137, 'イランのアルメニア教会修道院群', nan)
2022-05-02 17:46:54,989 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,990 INFO sqlalchemy.engine.base.Engine (138, '古代都市チョガー・ザンビール', nan)
2022-05-02 17:46:54,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,990 INFO sqlalchemy.engine.base.Engine (139, 'シューシュタルの歴史的水利システム', nan)
2022-05-02 17:46:54,990 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,991 INFO sqlalchemy.engine.base.Engine (140, 'ソルターニーイェ', nan)
2022-05-02 17:46:54,991 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,991 INFO sqlalchemy.engine.base.Engine (141, 'タフテ・ソレイマーン', nan)
2022-05-02 17:46:54,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,992 INFO sqlalchemy.engine.base.Engine (142, 'タブリーズの歴史的バザール群', nan)
2022-05-02 17:46:54,992 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,993 INFO sqlalchemy.engine.base.Engine (143, 'パサルガダエ', nan)
2022-05-02 17:46:54,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,993 INFO sqlalchemy.engine.base.Engine (144, 'バムとその文化的景観', nan)
2022-05-02 17:46:54,993 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,994 INFO sqlalchemy.engine.base.Engine (145, 'ビーソトゥーン', nan)
2022-05-02 17:46:54,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,994 INFO sqlalchemy.engine.base.Engine (146, 'ペルシア庭園', nan)
2022-05-02 17:46:54,994 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,995 INFO sqlalchemy.engine.base.Engine (147, 'ペルセポリス', nan)
2022-05-02 17:46:54,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,995 INFO sqlalchemy.engine.base.Engine (148, 'イスファハーンのマスジェデ・ジャーメ（金曜モスク）', nan)
2022-05-02 17:46:54,995 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,996 INFO sqlalchemy.engine.base.Engine (149, 'ゴンバデ・カーブース', nan)
2022-05-02 17:46:54,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,996 INFO sqlalchemy.engine.base.Engine (150, 'ゴレスタン宮殿', nan)
2022-05-02 17:46:54,996 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,996 INFO sqlalchemy.engine.base.Engine (151, 'ヤズドの歴史都市', nan)
2022-05-02 17:46:54,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:54,997 INFO sqlalchemy.engine.base.Engine (152, 'ヒルカニアの森林群 ', nan)
2022-05-02 17:46:54,997 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,998 INFO sqlalchemy.engine.base.Engine (153, 'シャフリ・ソフタ', nan)
2022-05-02 17:46:54,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,998 INFO sqlalchemy.engine.base.Engine (154, 'スーサ', nan)
2022-05-02 17:46:54,998 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,999 INFO sqlalchemy.engine.base.Engine (155, 'メイマンドの文化的景観', nan)
2022-05-02 17:46:54,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,999 INFO sqlalchemy.engine.base.Engine (156, 'ルート砂漠', nan)
2022-05-02 17:46:54,999 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:54,999 INFO sqlalchemy.engine.base.Engine (157, 'ペルシアのカナート', nan)
2022-05-02 17:46:55,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,000 INFO sqlalchemy.engine.base.Engine (158, 'ファールス地方にあるササン朝の考古学的景観', nan)
2022-05-02 17:46:55,000 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,000 INFO sqlalchemy.engine.base.Engine (159, 'イラン縦貫鉄道', nan)
2022-05-02 17:46:55,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,001 INFO sqlalchemy.engine.base.Engine (160, 'ホウラマン/ウラマナトの文化的景観', nan)
2022-05-02 17:46:55,001 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,001 INFO sqlalchemy.engine.base.Engine (161, 'アーグラ城', nan)
2022-05-02 17:46:55,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,002 INFO sqlalchemy.engine.base.Engine (162, 'アジャンターの石窟寺院群', nan)
2022-05-02 17:46:55,002 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,003 INFO sqlalchemy.engine.base.Engine (163, 'インドの山岳鉄道群', nan)
2022-05-02 17:46:55,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,003 INFO sqlalchemy.engine.base.Engine (164, 'エレファンタ島の石窟寺院群', nan)
2022-05-02 17:46:55,003 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,004 INFO sqlalchemy.engine.base.Engine (165, 'エローラーの石窟寺院群', nan)
2022-05-02 17:46:55,004 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,004 INFO sqlalchemy.engine.base.Engine (166, 'カジュラーホの寺院群', nan)
2022-05-02 17:46:55,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,005 INFO sqlalchemy.engine.base.Engine (167, 'カジランガ国立公園', nan)
2022-05-02 17:46:55,005 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,006 INFO sqlalchemy.engine.base.Engine (168, 'ケオラデオ国立公園', nan)
2022-05-02 17:46:55,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,006 INFO sqlalchemy.engine.base.Engine (169, 'ゴアの聖堂と修道院', nan)
2022-05-02 17:46:55,006 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,007 INFO sqlalchemy.engine.base.Engine (170, 'コナーラクのスーリヤ寺院', nan)
2022-05-02 17:46:55,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,007 INFO sqlalchemy.engine.base.Engine (171, 'サーンチーの仏教遺跡', nan)
2022-05-02 17:46:55,007 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,008 INFO sqlalchemy.engine.base.Engine (172, 'ジャイプールのジャンタル・マンタル－マハラジャの天文台', nan)
2022-05-02 17:46:55,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,008 INFO sqlalchemy.engine.base.Engine (173, 'スンダルバンス国立公園', nan)
2022-05-02 17:46:55,008 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,009 INFO sqlalchemy.engine.base.Engine (174, 'タージ・マハル', nan)
2022-05-02 17:46:55,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,009 INFO sqlalchemy.engine.base.Engine (175, '大チョーラ朝寺院群', nan)
2022-05-02 17:46:55,009 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,010 INFO sqlalchemy.engine.base.Engine (176, 'チャトラパティ・シヴァージー・ターミナス駅（旧名ヴィクトリア・ターミナス）', nan)
2022-05-02 17:46:55,010 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,010 INFO sqlalchemy.engine.base.Engine (177, 'チャンパネール ‐ パーヴァガドゥ遺跡公園', nan)
2022-05-02 17:46:55,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,011 INFO sqlalchemy.engine.base.Engine (178, 'デリーのクトゥブ・ミナールとその関連施設', nan)
2022-05-02 17:46:55,011 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,011 INFO sqlalchemy.engine.base.Engine (179, 'デリーのフマユーン廟', nan)
2022-05-02 17:46:55,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,012 INFO sqlalchemy.engine.base.Engine (180, 'ナンダ・デヴィ国立公園と花の谷国立公園', nan)
2022-05-02 17:46:55,012 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,013 INFO sqlalchemy.engine.base.Engine (181, 'パッタダカルの寺院群', nan)
2022-05-02 17:46:55,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,013 INFO sqlalchemy.engine.base.Engine (182, 'ハンピの都市遺跡', nan)
2022-05-02 17:46:55,013 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,014 INFO sqlalchemy.engine.base.Engine (183, 'ビンベットカのロック・シェルター群', nan)
2022-05-02 17:46:55,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,014 INFO sqlalchemy.engine.base.Engine (184, 'ファテープル・シークリー', nan)
2022-05-02 17:46:55,014 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,015 INFO sqlalchemy.engine.base.Engine (185, 'ブッダガヤの大菩提寺', nan)
2022-05-02 17:46:55,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,015 INFO sqlalchemy.engine.base.Engine (186, 'マナス野生動物保護区', nan)
2022-05-02 17:46:55,015 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,016 INFO sqlalchemy.engine.base.Engine (187, 'マハーバリプラムの建築と彫刻群', nan)
2022-05-02 17:46:55,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,016 INFO sqlalchemy.engine.base.Engine (188, 'レッド・フォート建造物群', nan)
2022-05-02 17:46:55,016 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,017 INFO sqlalchemy.engine.base.Engine (189, '西ガーツ山脈', nan)
2022-05-02 17:46:55,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,017 INFO sqlalchemy.engine.base.Engine (190, 'ラジャスタンの丘陵城塞群', nan)
2022-05-02 17:46:55,017 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,018 INFO sqlalchemy.engine.base.Engine (191, 'ラニ・キ・ヴァヴ：グジャラト州パタンにある王妃の階段井戸', nan)
2022-05-02 17:46:55,018 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,019 INFO sqlalchemy.engine.base.Engine (192, 'グレート・ヒマラヤ国立公園保護地区', nan)
2022-05-02 17:46:55,019 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,019 INFO sqlalchemy.engine.base.Engine (193, 'ナーランダ・マハーヴィハーラの遺跡群', nan)
2022-05-02 17:46:55,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,020 INFO sqlalchemy.engine.base.Engine (194, 'カンチェンジュンガ国立公園', nan)
2022-05-02 17:46:55,020 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,021 INFO sqlalchemy.engine.base.Engine (195, 'アーメダバードの歴史都市', nan)
2022-05-02 17:46:55,021 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,022 INFO sqlalchemy.engine.base.Engine (196, 'ムンバイにあるヴィクトリア朝ゴシックとアール・デコの建造物群', nan)
2022-05-02 17:46:55,022 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,023 INFO sqlalchemy.engine.base.Engine (197, 'ラジャスタン州のジャイプール市街', nan)
2022-05-02 17:46:55,023 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,023 INFO sqlalchemy.engine.base.Engine (198, 'テランガーナ州のカカティーヤ・ルドレシュワラ（ラマッパ）寺院', nan)
2022-05-02 17:46:55,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,024 INFO sqlalchemy.engine.base.Engine (199, 'ドーラヴィーラ：ハラッパーの都市', nan)
2022-05-02 17:46:55,024 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,024 INFO sqlalchemy.engine.base.Engine (200, 'ウジュン・クロン国立公園', nan)
2022-05-02 17:46:55,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,025 INFO sqlalchemy.engine.base.Engine (201, 'コモド国立公園', nan)
2022-05-02 17:46:55,025 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,025 INFO sqlalchemy.engine.base.Engine (202, '人類化石出土のサンギラン遺跡', nan)
2022-05-02 17:46:55,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,026 INFO sqlalchemy.engine.base.Engine (203, 'スマトラの熱帯雨林遺産', nan)
2022-05-02 17:46:55,026 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,027 INFO sqlalchemy.engine.base.Engine (204, 'プランバナンの寺院群', nan)
2022-05-02 17:46:55,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,027 INFO sqlalchemy.engine.base.Engine (205, 'ボロブドゥールの仏教寺院群', nan)
2022-05-02 17:46:55,027 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,028 INFO sqlalchemy.engine.base.Engine (206, 'ロレンツ国立公園', nan)
2022-05-02 17:46:55,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,028 INFO sqlalchemy.engine.base.Engine (207, 'バリの文化的景観：バリ・ヒンドゥー哲学トリ・ヒタ・カラナを表す水利システム「スバック」', nan)
2022-05-02 17:46:55,028 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,029 INFO sqlalchemy.engine.base.Engine (208, 'サワルントのオンビリン炭鉱遺産', nan)
2022-05-02 17:46:55,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,029 INFO sqlalchemy.engine.base.Engine (209, 'ヴァティカン市国', nan)
2022-05-02 17:46:55,029 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,030 INFO sqlalchemy.engine.base.Engine (210, 'カスビのブガンダ王国の王墓', nan)
2022-05-02 17:46:55,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,030 INFO sqlalchemy.engine.base.Engine (211, 'ブウィンディ原生国立公園', nan)
2022-05-02 17:46:55,030 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,030 INFO sqlalchemy.engine.base.Engine (212, 'ルウェンゾリ山地国立公園', nan)
2022-05-02 17:46:55,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,031 INFO sqlalchemy.engine.base.Engine (213, 'キエフ：聖ソフィア聖堂と関連修道院群、キエフ・ペチェルスカヤ大修道院', nan)
2022-05-02 17:46:55,031 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,031 INFO sqlalchemy.engine.base.Engine (214, 'ブコビナとダルマチアの府主教の邸宅', nan)
2022-05-02 17:46:55,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,032 INFO sqlalchemy.engine.base.Engine (215, 'リヴィウ歴史地区', nan)
2022-05-02 17:46:55,032 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,032 INFO sqlalchemy.engine.base.Engine (216, 'タウリカ半島の古代都市とチョーラ', nan)
2022-05-02 17:46:55,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,033 INFO sqlalchemy.engine.base.Engine (217, 'シュトルーヴェの測地弧', nan)
2022-05-02 17:46:55,033 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,033 INFO sqlalchemy.engine.base.Engine (218, 'シャフリサブズの歴史地区', nan)
2022-05-02 17:46:55,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,034 INFO sqlalchemy.engine.base.Engine (219, 'ヒヴァのイチャン・カラ', nan)
2022-05-02 17:46:55,034 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,034 INFO sqlalchemy.engine.base.Engine (220, 'ブハラの歴史地区', nan)
2022-05-02 17:46:55,035 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,035 INFO sqlalchemy.engine.base.Engine (221, '文化交差路サマルカンド', nan)
2022-05-02 17:46:55,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,036 INFO sqlalchemy.engine.base.Engine (222, 'コロニア・デル・サクラメントの歴史地区', nan)
2022-05-02 17:46:55,036 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,036 INFO sqlalchemy.engine.base.Engine (223, 'フライ・ベントスの産業景観', nan)
2022-05-02 17:46:55,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,037 INFO sqlalchemy.engine.base.Engine (224, '技術者エラディオ・ディエステの作品：アトランティーダの教会', nan)
2022-05-02 17:46:55,037 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,038 INFO sqlalchemy.engine.base.Engine (225, 'ジョドレルバンク天文台', nan)
2022-05-02 17:46:55,038 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,082 INFO sqlalchemy.engine.base.Engine (226, 'アイアンブリッジ峡谷', nan)
2022-05-02 17:46:55,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,083 INFO sqlalchemy.engine.base.Engine (227, 'ウェストミンスター宮殿、ウェストミンスター・アビーとセント・マーガレット教会', nan)
2022-05-02 17:46:55,083 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,083 INFO sqlalchemy.engine.base.Engine (228, 'エディンバラの旧市街と新市街', nan)
2022-05-02 17:46:55,084 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,084 INFO sqlalchemy.engine.base.Engine (229, 'オークニー諸島の新石器時代遺跡', nan)
2022-05-02 17:46:55,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,085 INFO sqlalchemy.engine.base.Engine (230, '海事都市グリニッジ', nan)
2022-05-02 17:46:55,085 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,086 INFO sqlalchemy.engine.base.Engine (231, 'カンタベリー大聖堂、セント・オーガスティン修道院跡とセント・マーティン教会', nan)
2022-05-02 17:46:55,086 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,087 INFO sqlalchemy.engine.base.Engine (232, 'キューの王立植物園', nan)
2022-05-02 17:46:55,087 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,088 INFO sqlalchemy.engine.base.Engine (233, 'グウィネズのエドワード1世王の城郭群', nan)
2022-05-02 17:46:55,088 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,088 INFO sqlalchemy.engine.base.Engine (234, 'コーンウォールと西デヴォンの鉱山景観', nan)
2022-05-02 17:46:55,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,090 INFO sqlalchemy.engine.base.Engine (235, 'ゴフ島及びインアクセシブル島', nan)
2022-05-02 17:46:55,090 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,091 INFO sqlalchemy.engine.base.Engine (236, 'ジャイアンツ・コーズウェイとその海岸', nan)
2022-05-02 17:46:55,091 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,092 INFO sqlalchemy.engine.base.Engine (237, 'ファウンテンズ修道院の廃墟のあるスタッドリー・ロイヤル公園', nan)
2022-05-02 17:46:55,092 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,092 INFO sqlalchemy.engine.base.Engine (238, 'ストーンヘンジ、エイヴベリーの巨石遺跡と関連遺跡群', nan)
2022-05-02 17:46:55,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,093 INFO sqlalchemy.engine.base.Engine (239, 'セント・キルダ諸島', nan)
2022-05-02 17:46:55,093 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,094 INFO sqlalchemy.engine.base.Engine (240, 'ソルテア', nan)
2022-05-02 17:46:55,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,094 INFO sqlalchemy.engine.base.Engine (241, 'ダーウェント峡谷の工場群', nan)
2022-05-02 17:46:55,094 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,095 INFO sqlalchemy.engine.base.Engine (242, 'ダラム城と大聖堂', nan)
2022-05-02 17:46:55,095 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,095 INFO sqlalchemy.engine.base.Engine (243, 'ドーセット及び東デヴォン海岸', nan)
2022-05-02 17:46:55,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,096 INFO sqlalchemy.engine.base.Engine (244, 'ニュー・ラナーク', nan)
2022-05-02 17:46:55,096 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,096 INFO sqlalchemy.engine.base.Engine (245, 'バースの市街', nan)
2022-05-02 17:46:55,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,097 INFO sqlalchemy.engine.base.Engine (246, 'バミューダ諸島：歴史的都市セント・ジョージと関連要塞群', nan)
2022-05-02 17:46:55,097 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,097 INFO sqlalchemy.engine.base.Engine (247, 'ブレナヴォン産業景観', nan)
2022-05-02 17:46:55,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,098 INFO sqlalchemy.engine.base.Engine (248, 'ブレナム宮殿', nan)
2022-05-02 17:46:55,098 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,098 INFO sqlalchemy.engine.base.Engine (249, 'ヘンダーソン島', nan)
2022-05-02 17:46:55,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,099 INFO sqlalchemy.engine.base.Engine (250, 'ポントカサステ水路橋と運河', nan)
2022-05-02 17:46:55,099 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,099 INFO sqlalchemy.engine.base.Engine (251, 'ロンドン塔', nan)
2022-05-02 17:46:55,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,100 INFO sqlalchemy.engine.base.Engine (252, 'ローマ帝国の境界線', nan)
2022-05-02 17:46:55,100 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,100 INFO sqlalchemy.engine.base.Engine (253, 'フォース鉄道橋', nan)
2022-05-02 17:46:55,101 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,101 INFO sqlalchemy.engine.base.Engine (254, 'ウェールズ北西部の粘板岩の景観', nan)
2022-05-02 17:46:55,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,102 INFO sqlalchemy.engine.base.Engine (255, 'ゴーハムの洞窟群', nan)
2022-05-02 17:46:55,102 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,102 INFO sqlalchemy.engine.base.Engine (256, '英国の湖水地方', nan)
2022-05-02 17:46:55,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,103 INFO sqlalchemy.engine.base.Engine (257, 'ガラパゴス諸島', nan)
2022-05-02 17:46:55,103 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,103 INFO sqlalchemy.engine.base.Engine (258, 'キトの市街', nan)
2022-05-02 17:46:55,104 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,104 INFO sqlalchemy.engine.base.Engine (259, 'クエンカのサンタ・アナ・デ・ロス・リオス歴史地区', nan)
2022-05-02 17:46:55,105 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,105 INFO sqlalchemy.engine.base.Engine (260, 'サンガイ国立公園', nan)
2022-05-02 17:46:55,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,106 INFO sqlalchemy.engine.base.Engine (261, 'カイロの歴史地区', nan)
2022-05-02 17:46:55,106 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,107 INFO sqlalchemy.engine.base.Engine (262, '古代都市テーベと墓地遺跡', nan)
2022-05-02 17:46:55,107 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,107 INFO sqlalchemy.engine.base.Engine (263, '聖カトリーナ修道院地域', nan)
2022-05-02 17:46:55,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,108 INFO sqlalchemy.engine.base.Engine (264, '聖都アブー・メナー', nan)
2022-05-02 17:46:55,108 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,108 INFO sqlalchemy.engine.base.Engine (265, 'ヌビアの遺跡群：アブ・シンベルからフィラエまで', nan)
2022-05-02 17:46:55,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,109 INFO sqlalchemy.engine.base.Engine (266, 'メンフィスのピラミッド地帯', nan)
2022-05-02 17:46:55,109 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,109 INFO sqlalchemy.engine.base.Engine (267, 'ワディ・アル・ヒタン（鯨の谷）', nan)

2022-05-02 17:46:55,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,110 INFO sqlalchemy.engine.base.Engine (268, 'タリンの歴史地区', nan)
2022-05-02 17:46:55,110 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,110 INFO sqlalchemy.engine.base.Engine (269, 'アクスムの考古遺跡', nan)
2022-05-02 17:46:55,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,111 INFO sqlalchemy.engine.base.Engine (270, 'アワッシュ川下流域', nan)
2022-05-02 17:46:55,111 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,112 INFO sqlalchemy.engine.base.Engine (271, 'オモ川下流域', nan)
2022-05-02 17:46:55,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,112 INFO sqlalchemy.engine.base.Engine (272, 'コンソの文化的景観', nan)
2022-05-02 17:46:55,112 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,113 INFO sqlalchemy.engine.base.Engine (273, 'シミエン国立公園', nan)
2022-05-02 17:46:55,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,113 INFO sqlalchemy.engine.base.Engine (275, 'ティヤの石碑群', nan)
2022-05-02 17:46:55,113 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,114 INFO sqlalchemy.engine.base.Engine (279, 'ホヤ・デ・セレンの考古遺跡', nan)
2022-05-02 17:46:55,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,114 INFO sqlalchemy.engine.base.Engine (280, 'エルサレムの旧市街とその城壁群', nan)
2022-05-02 17:46:55,114 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,115 INFO sqlalchemy.engine.base.Engine (281, 'ウィランドラ湖地域', nan)
2022-05-02 17:46:55,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,115 INFO sqlalchemy.engine.base.Engine (283, '王立展示館とカールトン庭園', nan)
2022-05-02 17:46:55,115 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,116 INFO sqlalchemy.engine.base.Engine (284, 'オーストラリアのゴンドワナ雨林', nan)
2022-05-02 17:46:55,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,116 INFO sqlalchemy.engine.base.Engine (285, 'オーストラリアの囚人収容所遺跡群', nan)
2022-05-02 17:46:55,116 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,116 INFO sqlalchemy.engine.base.Engine (287, 'カカドゥ国立公園', nan)
2022-05-02 17:46:55,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,117 INFO sqlalchemy.engine.base.Engine (288, 'クイーンズランドの湿潤熱帯地域', nan)
2022-05-02 17:46:55,117 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,117 INFO sqlalchemy.engine.base.Engine (289, 'グレート・バリア・リーフ', nan)
2022-05-02 17:46:55,118 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,118 INFO sqlalchemy.engine.base.Engine (290, 'シドニーのオペラハウス', nan)
2022-05-02 17:46:55,119 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,119 INFO sqlalchemy.engine.base.Engine (291, 'シャーク湾', nan)
2022-05-02 17:46:55,120 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,120 INFO sqlalchemy.engine.base.Engine (292, 'タスマニア原生地帯', nan)
2022-05-02 17:46:55,121 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,121 INFO sqlalchemy.engine.base.Engine (293, 'ニンガルー・コースト', nan)
2022-05-02 17:46:55,122 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,122 INFO sqlalchemy.engine.base.Engine (294, 'ハード島とマクドナルド諸島', nan)
2022-05-02 17:46:55,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,123 INFO sqlalchemy.engine.base.Engine (295, 'パーヌルル国立公園', nan)
2022-05-02 17:46:55,123 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,124 INFO sqlalchemy.engine.base.Engine (296, 'ブルー・マウンテンズ地域', nan)
2022-05-02 17:46:55,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,124 INFO sqlalchemy.engine.base.Engine (297, 'フレーザー島', nan)
2022-05-02 17:46:55,124 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,125 INFO sqlalchemy.engine.base.Engine (298, 'マックォーリー島', nan)
2022-05-02 17:46:55,125 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,125 INFO sqlalchemy.engine.base.Engine (299, 'ロード・ハウ群島', nan)
2022-05-02 17:46:55,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,126 INFO sqlalchemy.engine.base.Engine (301, 'ヴァッハウ渓谷の文化的景観', nan)
2022-05-02 17:46:55,126 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,126 INFO sqlalchemy.engine.base.Engine (302, 'ウィーンの歴史地区', nan)
2022-05-02 17:46:55,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,127 INFO sqlalchemy.engine.base.Engine (303, 'グラーツ：歴史地区とエッゲンベルク城', nan)
2022-05-02 17:46:55,127 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,127 INFO sqlalchemy.engine.base.Engine (304, 'ザルツブルクの歴史地区', nan)
2022-05-02 17:46:55,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,128 INFO sqlalchemy.engine.base.Engine (305, 'シェーンブルン宮殿と庭園', nan)
2022-05-02 17:46:55,128 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,128 INFO sqlalchemy.engine.base.Engine (306, 'ゼメリング鉄道', nan)
2022-05-02 17:46:55,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,129 INFO sqlalchemy.engine.base.Engine (307, 'ハルシュタット＝ダッハシュタイン/ザルツカンマーグートの文化的景観', nan)
2022-05-02 17:46:55,129 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,129 INFO sqlalchemy.engine.base.Engine (311, 'アフラージュ－オマーンの灌漑システム', nan)
2022-05-02 17:46:55,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,130 INFO sqlalchemy.engine.base.Engine (312, '乳香の大地：交易路と関連遺跡群', nan)
2022-05-02 17:46:55,130 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,130 INFO sqlalchemy.engine.base.Engine (313, 'バット、アル・フトゥム、アル・アインの考古遺跡', nan)
2022-05-02 17:46:55,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,131 INFO sqlalchemy.engine.base.Engine (314, 'バフラの砦', nan)
2022-05-02 17:46:55,131 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,131 INFO sqlalchemy.engine.base.Engine (316, 'アムステルダム中心部：ジンフェルグラハト内部の17世紀の環状運河地区', nan)
2022-05-02 17:46:55,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,132 INFO sqlalchemy.engine.base.Engine (317, 'オランダの水利防衛線群（旧遺産名：アムステルダムの防衛線の要塞）', nan)
2022-05-02 17:46:55,132 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,132 INFO sqlalchemy.engine.base.Engine (318, 'ウィレムスタットの歴史地区：キュラソーにある内陸都市と港', nan)
2022-05-02 17:46:55,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,133 INFO sqlalchemy.engine.base.Engine (319, 'キンデルダイク-エルスハウトの風車群', nan)
2022-05-02 17:46:55,133 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,133 INFO sqlalchemy.engine.base.Engine (320, 'スホクラントと周辺の干拓地', nan)
2022-05-02 17:46:55,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,134 INFO sqlalchemy.engine.base.Engine (321, 'Ir.D.F.ヴァウダヘマール：D.F.ヴァウダ技師による蒸気水揚げポンプ場', nan)
2022-05-02 17:46:55,134 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,135 INFO sqlalchemy.engine.base.Engine (322, 'ベームスター干拓地（ドゥローフマーケライ・デ・ベームスター）', nan)
2022-05-02 17:46:55,135 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,135 INFO sqlalchemy.engine.base.Engine (323, 'リートフェルト設計のシュレーダー邸', nan)
2022-05-02 17:46:55,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,136 INFO sqlalchemy.engine.base.Engine (324, 'ファン・ネレ工場', nan)
2022-05-02 17:46:55,136 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,136 INFO sqlalchemy.engine.base.Engine (325, 'アシャンティ族の伝統的建造物群', nan)
2022-05-02 17:46:55,137 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,137 INFO sqlalchemy.engine.base.Engine (326, 'ガーナのベナン湾沿いの城塞群', nan)
2022-05-02 17:46:55,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,138 INFO sqlalchemy.engine.base.Engine (327, 'シダーデ・ヴェーリャ、リベイラ・グランデの歴史地区', nan)
2022-05-02 17:46:55,138 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,139 INFO sqlalchemy.engine.base.Engine (328, 'サリアルカ：北部カザフスタンの草原と湖群', nan)
2022-05-02 17:46:55,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,139 INFO sqlalchemy.engine.base.Engine (329, 'タムガリの考古的景観にある岩絵群', nan)
2022-05-02 17:46:55,139 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,140 INFO sqlalchemy.engine.base.Engine (330, 'ホージャ・アフマド・ヤサヴィー廟', nan)
2022-05-02 17:46:55,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,140 INFO sqlalchemy.engine.base.Engine (332, 'アル・ズバラ考古学的地区', nan)
2022-05-02 17:46:55,140 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,141 INFO sqlalchemy.engine.base.Engine (333, 'ウッド・バッファロー国立公園', nan)
2022-05-02 17:46:55,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,141 INFO sqlalchemy.engine.base.Engine (334, 'カナディアン・ロッキー山脈国立公園群', nan)
2022-05-02 17:46:55,141 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,142 INFO sqlalchemy.engine.base.Engine (335, 'グロス・モーン国立公園', nan)
2022-05-02 17:46:55,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,142 INFO sqlalchemy.engine.base.Engine (336, 'ケベック旧市街の歴史地区', nan)
2022-05-02 17:46:55,142 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,143 INFO sqlalchemy.engine.base.Engine (337, 'ジョギンズの化石断崖群', nan)
2022-05-02 17:46:55,143 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,143 INFO sqlalchemy.engine.base.Engine (338, 'スカン・グアイ', nan)
2022-05-02 17:46:55,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,144 INFO sqlalchemy.engine.base.Engine (339, 'ダイナソール州立公園', nan)
2022-05-02 17:46:55,144 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,144 INFO sqlalchemy.engine.base.Engine (340, 'ナハニ国立公園', nan)
2022-05-02 17:46:55,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,145 INFO sqlalchemy.engine.base.Engine (341, 'バッファロー狩りの断崖', nan)
2022-05-02 17:46:55,145 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,145 INFO sqlalchemy.engine.base.Engine (342, 'ミグアシャ国立公園', nan)
2022-05-02 17:46:55,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,146 INFO sqlalchemy.engine.base.Engine (343, 'ランス・オー・メドー国立歴史公園', nan)
2022-05-02 17:46:55,146 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,146 INFO sqlalchemy.engine.base.Engine (344, 'リドー運河', nan)
2022-05-02 17:46:55,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,147 INFO sqlalchemy.engine.base.Engine (345, 'ルーネンバーグの旧市街', nan)
2022-05-02 17:46:55,147 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,147 INFO sqlalchemy.engine.base.Engine (346, 'グラン・プレの景観', nan)
2022-05-02 17:46:55,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,148 INFO sqlalchemy.engine.base.Engine (347, 'レッド・ベイのバスク人捕鯨基地', nan)
2022-05-02 17:46:55,148 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,148 INFO sqlalchemy.engine.base.Engine (353, 'ジャー動物保護区', nan)
2022-05-02 17:46:55,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,149 INFO sqlalchemy.engine.base.Engine (354, 'サンガ川流域－三カ国を流れる大河', nan)
2022-05-02 17:46:55,149 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,149 INFO sqlalchemy.engine.base.Engine (356, 'セネガンビアのストーン・サークル遺跡群', nan)
2022-05-02 17:46:55,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,150 INFO sqlalchemy.engine.base.Engine (358, 'プレア・ビヒア寺院', nan)
2022-05-02 17:46:55,150 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,150 INFO sqlalchemy.engine.base.Engine (360, '高句麗古墳群', nan)
2022-05-02 17:46:55,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,151 INFO sqlalchemy.engine.base.Engine (361, '開城歴史遺跡地区', nan)
2022-05-02 17:46:55,151 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,151 INFO sqlalchemy.engine.base.Engine (362, 'オフリド地方の自然及び文化遺産', nan)
2022-05-02 17:46:55,152 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,152 INFO sqlalchemy.engine.base.Engine (363, 'ニンバ山厳正自然保護区', nan)
2022-05-02 17:46:55,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,153 INFO sqlalchemy.engine.base.Engine (364, 'トロオドス地方の壁画教会群', nan)
2022-05-02 17:46:55,153 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,154 INFO sqlalchemy.engine.base.Engine (365, 'パフォスの考古遺跡', nan)
2022-05-02 17:46:55,154 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,154 INFO sqlalchemy.engine.base.Engine (366, 'ヒロキティアの考古遺跡', nan)
2022-05-02 17:46:55,155 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,155 INFO sqlalchemy.engine.base.Engine (367, 'アレハンドロ・デ・フンボルト国立公園', nan)
2022-05-02 17:46:55,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,156 INFO sqlalchemy.engine.base.Engine (368, 'カマグエイの歴史地区', nan)
2022-05-02 17:46:55,156 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,157 INFO sqlalchemy.engine.base.Engine (369, 'キューバ南東部におけるコーヒー農園発祥地の景観', nan)
2022-05-02 17:46:55,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,157 INFO sqlalchemy.engine.base.Engine (370, 'グランマ号上陸記念国立公園', nan)
2022-05-02 17:46:55,157 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,215 INFO sqlalchemy.engine.base.Engine (371, 'サンティアゴ・デ・クーバのサン・ペドロ・デ・ラ・ロカ城', nan)
2022-05-02 17:46:55,216 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,216 INFO sqlalchemy.engine.base.Engine (372, 'シエンフエゴスの歴史地区', nan)
2022-05-02 17:46:55,217 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,217 INFO sqlalchemy.engine.base.Engine (373, 'トリニダとロス・インヘニオス渓谷', nan)
2022-05-02 17:46:55,218 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,218 INFO sqlalchemy.engine.base.Engine (374, 'ハバナの旧市街と要塞群', nan)
2022-05-02 17:46:55,219 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,219 INFO sqlalchemy.engine.base.Engine (375, 'ビニャーレス渓谷', nan)
2022-05-02 17:46:55,220 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,220 INFO sqlalchemy.engine.base.Engine (377, 'ヴァッセのアポロン・エピクリオス神殿', nan)
2022-05-02 17:46:55,221 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,222 INFO sqlalchemy.engine.base.Engine (378, 'エゲ（現代名ヴェルギナ）の考古遺跡', nan)
2022-05-02 17:46:55,223 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,223 INFO sqlalchemy.engine.base.Engine (379, 'エピダウロスにあるアスクレピオスの聖域', nan)
2022-05-02 17:46:55,224 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,224 INFO sqlalchemy.engine.base.Engine (380, 'オリンピアの考古遺跡', nan)
2022-05-02 17:46:55,225 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,226 INFO sqlalchemy.engine.base.Engine (381, 'コルフの旧市街', nan)
2022-05-02 17:46:55,227 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,227 INFO sqlalchemy.engine.base.Engine (382, 'サモス島のピタゴリオンとヘラ神殿', nan)
2022-05-02 17:46:55,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,228 INFO sqlalchemy.engine.base.Engine (383, '聖山アトス', nan)
2022-05-02 17:46:55,228 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,228 INFO sqlalchemy.engine.base.Engine (384, 'パトモス島にある歴史地区（ホラ）：神学者聖ヨハネの修道院と黙示録の洞窟', nan)
2022-05-02 17:46:55,229 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,229 INFO sqlalchemy.engine.base.Engine (385, 'ダフニ、オシオス・ルカス、ヒオスのネア・モニの修道院群', nan)
2022-05-02 17:46:55,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,230 INFO sqlalchemy.engine.base.Engine (386, 'テサロニキの初期キリスト教とビザンツ様式の建造物群', nan)
2022-05-02 17:46:55,230 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,231 INFO sqlalchemy.engine.base.Engine (387, 'デルフィの考古遺跡', nan)
2022-05-02 17:46:55,231 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,231 INFO sqlalchemy.engine.base.Engine (388, 'デロス島', nan)
2022-05-02 17:46:55,232 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,232 INFO sqlalchemy.engine.base.Engine (389, 'ミケーネとティリンスの考古遺跡', nan)
2022-05-02 17:46:55,233 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,233 INFO sqlalchemy.engine.base.Engine (390, 'ミストラの考古遺跡', nan)
2022-05-02 17:46:55,234 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,234 INFO sqlalchemy.engine.base.Engine (391, 'メテオラの修道院群', nan)
2022-05-02 17:46:55,235 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,235 INFO sqlalchemy.engine.base.Engine (392, 'ロドス島の中世都市', nan)
2022-05-02 17:46:55,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,237 INFO sqlalchemy.engine.base.Engine (394, 'フェニックス諸島保護地域', nan)
2022-05-02 17:46:55,237 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,237 INFO sqlalchemy.engine.base.Engine (395, '聖山スレイマン・トー', nan)
2022-05-02 17:46:55,238 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,238 INFO sqlalchemy.engine.base.Engine (396, 'アンティグア・グアテマラ', nan)
2022-05-02 17:46:55,239 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,240 INFO sqlalchemy.engine.base.Engine (397, 'キリグア遺跡公園', nan)
2022-05-02 17:46:55,240 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,241 INFO sqlalchemy.engine.base.Engine (398, 'ティカル国立公園', nan)
2022-05-02 17:46:55,241 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,241 INFO sqlalchemy.engine.base.Engine (400, 'シベニクの聖ヤコブ大聖堂', nan)
2022-05-02 17:46:55,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,242 INFO sqlalchemy.engine.base.Engine (401, 'スプリトのディオクレティアヌス帝の宮殿と歴史的建造物群', nan)
2022-05-02 17:46:55,242 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,243 INFO sqlalchemy.engine.base.Engine (402, 'ドゥブロヴニクの旧市街', nan)
2022-05-02 17:46:55,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,244 INFO sqlalchemy.engine.base.Engine (403, 'フヴァル島のスターリ・グラード平地', nan)
2022-05-02 17:46:55,244 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,245 INFO sqlalchemy.engine.base.Engine (404, 'プリトヴィツェ湖群国立公園', nan)
2022-05-02 17:46:55,246 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,246 INFO sqlalchemy.engine.base.Engine (405, 'ポレチュ歴史地区にあるエウフラシウス聖堂の司教関連建造物群', nan)

2022-05-02 17:46:55,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,247 INFO sqlalchemy.engine.base.Engine (406, '歴史都市トロギール', nan)
2022-05-02 17:46:55,247 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,248 INFO sqlalchemy.engine.base.Engine (409, 'トゥルカナ湖国立公園群', nan)
2022-05-02 17:46:55,248 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,249 INFO sqlalchemy.engine.base.Engine (414, 'コモエ国立公園', nan)
2022-05-02 17:46:55,249 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,249 INFO sqlalchemy.engine.base.Engine (415, 'タイ国立公園', nan)
2022-05-02 17:46:55,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,250 INFO sqlalchemy.engine.base.Engine (416, 'グラン・バッサムの歴史都市', nan)
2022-05-02 17:46:55,250 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,251 INFO sqlalchemy.engine.base.Engine (418, 'グアナカステ保護地区', nan)
2022-05-02 17:46:55,251 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,252 INFO sqlalchemy.engine.base.Engine (419, 'ココス島国立公園', nan)
2022-05-02 17:46:55,253 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,253 INFO sqlalchemy.engine.base.Engine (420, 'ディキスの石球のある先コロンブス期の首長制集落群', nan)
2022-05-02 17:46:55,255 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,256 INFO sqlalchemy.engine.base.Engine (422, 'カルタヘナの港、要塞、歴史的建造物群', nan)
2022-05-02 17:46:55,257 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,257 INFO sqlalchemy.engine.base.Engine (423, 'コロンビアのコーヒー農園の文化的景観', nan)
2022-05-02 17:46:55,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,258 INFO sqlalchemy.engine.base.Engine (424, 'サン・アグスティン考古公園', nan)
2022-05-02 17:46:55,258 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,259 INFO sqlalchemy.engine.base.Engine (425, 'サンタ・クルス・デ・モンポスの歴史地区', nan)
2022-05-02 17:46:55,259 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,260 INFO sqlalchemy.engine.base.Engine (426, 'ティエラデントロ国立考古公園', nan)
2022-05-02 17:46:55,260 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,261 INFO sqlalchemy.engine.base.Engine (427, 'マルペロ動植物保護区', nan)
2022-05-02 17:46:55,261 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,262 INFO sqlalchemy.engine.base.Engine (428, 'ロス・カティオス国立公園', nan)
2022-05-02 17:46:55,262 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,263 INFO sqlalchemy.engine.base.Engine (430, 'ヴィルンガ国立公園', nan)
2022-05-02 17:46:55,263 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,263 INFO sqlalchemy.engine.base.Engine (431, 'オカピ野生動物保護区', nan)
2022-05-02 17:46:55,264 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,264 INFO sqlalchemy.engine.base.Engine (432, 'カフジ・ビエガ国立公園', nan)
2022-05-02 17:46:55,265 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,265 INFO sqlalchemy.engine.base.Engine (433, 'ガランバ国立公園', nan)
2022-05-02 17:46:55,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,266 INFO sqlalchemy.engine.base.Engine (434, 'サロンガ国立公園', nan)
2022-05-02 17:46:55,266 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,267 INFO sqlalchemy.engine.base.Engine (435, 'アル・ヒジルの考古遺跡（マダイン・サレハ）', nan)
2022-05-02 17:46:55,267 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,268 INFO sqlalchemy.engine.base.Engine (436, 'ディライーヤのツライフ地区', nan)
2022-05-02 17:46:55,269 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,270 INFO sqlalchemy.engine.base.Engine (437, 'ジッダの歴史地区：メッカの入口', nan)
2022-05-02 17:46:55,270 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,272 INFO sqlalchemy.engine.base.Engine (438, 'サウジアラビアのハーイル地方にある壁画', nan)
2022-05-02 17:46:55,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,273 INFO sqlalchemy.engine.base.Engine (441, 'サン・マリノの歴史地区とティタノ山', nan)
2022-05-02 17:46:55,273 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,274 INFO sqlalchemy.engine.base.Engine (443, 'ブルー・アンド・ジョン・クロウ山脈', nan)
2022-05-02 17:46:55,274 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,275 INFO sqlalchemy.engine.base.Engine (444, '上スヴァネチア', nan)
2022-05-02 17:46:55,275 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,275 INFO sqlalchemy.engine.base.Engine (445, 'ゲラティ修道院', nan)
2022-05-02 17:46:55,276 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,276 INFO sqlalchemy.engine.base.Engine (446, 'ムツヘタの歴史的建造物群', nan)
2022-05-02 17:46:55,277 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,277 INFO sqlalchemy.engine.base.Engine (448, 'アレッポの旧市街', nan)
2022-05-02 17:46:55,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,278 INFO sqlalchemy.engine.base.Engine (449, 'クラック・デ・シュヴァリエとカラット・サラーフ・アッディーン', nan)
2022-05-02 17:46:55,278 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,279 INFO sqlalchemy.engine.base.Engine (450, '古代都市パルミラ', nan)
2022-05-02 17:46:55,279 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,279 INFO sqlalchemy.engine.base.Engine (451, 'シリア北部の古代集落群', nan)
2022-05-02 17:46:55,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,280 INFO sqlalchemy.engine.base.Engine (452, '隊商都市ボスラ', nan)
2022-05-02 17:46:55,280 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,281 INFO sqlalchemy.engine.base.Engine (453, 'ダマスカスの旧市街', nan)
2022-05-02 17:46:55,282 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,282 INFO sqlalchemy.engine.base.Engine (454, 'シンガポール植物園', nan)
2022-05-02 17:46:55,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,283 INFO sqlalchemy.engine.base.Engine (455, 'カミ遺跡', nan)
2022-05-02 17:46:55,283 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,284 INFO sqlalchemy.engine.base.Engine (459, 'ザンクト・ガレンの修道院', nan)
2022-05-02 17:46:55,285 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,286 INFO sqlalchemy.engine.base.Engine (460, 'スイスのサルドナ上層地殻変動地帯', nan)
2022-05-02 17:46:55,286 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,287 INFO sqlalchemy.engine.base.Engine (461, 'ベリンツォーナ旧市街にある三つの城、城壁と要塞群', nan)
2022-05-02 17:46:55,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,290 INFO sqlalchemy.engine.base.Engine (462, 'ベルンの旧市街', nan)
2022-05-02 17:46:55,290 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,292 INFO sqlalchemy.engine.base.Engine (463, 'ミュスタイアにあるベネディクト会の聖ヨハネ修道院', nan)
2022-05-02 17:46:55,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,293 INFO sqlalchemy.engine.base.Engine (464, 'ユングフラウ－アレッチュのスイス・アルプス', nan)
2022-05-02 17:46:55,293 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,294 INFO sqlalchemy.engine.base.Engine (465, 'ラヴォー地域のブドウ畑', nan)
2022-05-02 17:46:55,294 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,295 INFO sqlalchemy.engine.base.Engine (467, 'ヘルシングランドの装飾された農夫の家', nan)
2022-05-02 17:46:55,295 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,295 INFO sqlalchemy.engine.base.Engine (468, 'ヴァールベリのグリメトン無線局', nan)
2022-05-02 17:46:55,296 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,297 INFO sqlalchemy.engine.base.Engine (469, 'エーランド島南部の農業景観', nan)
2022-05-02 17:46:55,298 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,298 INFO sqlalchemy.engine.base.Engine (470, 'エンゲルスベリの製鉄所', nan)
2022-05-02 17:46:55,299 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,300 INFO sqlalchemy.engine.base.Engine (471, 'カールスクローナの軍港', nan)
2022-05-02 17:46:55,300 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,300 INFO sqlalchemy.engine.base.Engine (472, 'ルーレオにあるガンメルスタードの教会街', nan)
2022-05-02 17:46:55,301 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,301 INFO sqlalchemy.engine.base.Engine (473, 'サーメ人地域', nan)
2022-05-02 17:46:55,302 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,302 INFO sqlalchemy.engine.base.Engine (474, 'スクーグスシルコゴーデンの森林墓地', nan)
2022-05-02 17:46:55,303 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,305 INFO sqlalchemy.engine.base.Engine (475, 'タヌムの岩絵群', nan)
2022-05-02 17:46:55,306 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,306 INFO sqlalchemy.engine.base.Engine (476, 'ドロットニングホルムの王領地', nan)
2022-05-02 17:46:55,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,308 INFO sqlalchemy.engine.base.Engine (477, 'ハンザ都市ヴィスビー', nan)
2022-05-02 17:46:55,308 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,309 INFO sqlalchemy.engine.base.Engine (478, 'ビルカとホヴゴーデン', nan)
2022-05-02 17:46:55,311 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,311 INFO sqlalchemy.engine.base.Engine (479, 'ファールンの大銅山地域', nan)
2022-05-02 17:46:55,312 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,313 INFO sqlalchemy.engine.base.Engine (481, 'ゲベル・バルカルとナパタ地域の遺跡群', nan)
2022-05-02 17:46:55,314 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,314 INFO sqlalchemy.engine.base.Engine (484, 'アストゥリアス王国とオビエドの宗教建築物群', nan)
2022-05-02 17:46:55,315 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,315 INFO sqlalchemy.engine.base.Engine (485, 'アタプエルカの考古遺跡群', nan)
2022-05-02 17:46:55,316 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,317 INFO sqlalchemy.engine.base.Engine (486, 'アビラの旧市街と城壁外の教会群', nan)
2022-05-02 17:46:55,318 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,319 INFO sqlalchemy.engine.base.Engine (487, 'アラゴンのムデハル様式建築', nan)
2022-05-02 17:46:55,321 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,322 INFO sqlalchemy.engine.base.Engine (488, 'アランフエスの文化的景観', nan)
2022-05-02 17:46:55,324 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,324 INFO sqlalchemy.engine.base.Engine (489, 'アルカラ・デ・エナレスの大学と歴史地区', nan)
2022-05-02 17:46:55,325 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,325 INFO sqlalchemy.engine.base.Engine (490, 'アルタミラ洞窟とスペイン北部の旧石器時代洞窟壁画', nan)
2022-05-02 17:46:55,326 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,326 INFO sqlalchemy.engine.base.Engine (492, 'イビサ島の生物多様性と文化', nan)
2022-05-02 17:46:55,328 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,329 INFO sqlalchemy.engine.base.Engine (493, 'イベリア半島の地中海沿岸の岩絵群', nan)
2022-05-02 17:46:55,330 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,331 INFO sqlalchemy.engine.base.Engine (494, 'ウベダとバエーサのルネサンス様式の記念碑的建造物群', nan)
2022-05-02 17:46:55,332 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,333 INFO sqlalchemy.engine.base.Engine (495, 'エルチェの椰子園', nan)
2022-05-02 17:46:55,335 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,335 INFO sqlalchemy.engine.base.Engine (496, 'カセレスの旧市街', nan)
2022-05-02 17:46:55,337 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,338 INFO sqlalchemy.engine.base.Engine (497, 'ガラホナイ国立公園', nan)
2022-05-02 17:46:55,339 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,341 INFO sqlalchemy.engine.base.Engine (498, 'グラナダのアルハンブラ宮殿、ヘネラリーフェ離宮、アルバイシン地区', nan)
2022-05-02 17:46:55,341 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,341 INFO sqlalchemy.engine.base.Engine (499, 'コルドバの歴史地区', nan)
2022-05-02 17:46:55,342 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,344 INFO sqlalchemy.engine.base.Engine (500, 'サラマンカの旧市街', nan)
2022-05-02 17:46:55,344 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,345 INFO sqlalchemy.engine.base.Engine (501, 'サン・クリストバル・デ・ラ・ラグナ', nan)
2022-05-02 17:46:55,346 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,347 INFO sqlalchemy.engine.base.Engine (502, 'サンタ・マリア・デ・グアダルーペ王立修道院', nan)
2022-05-02 17:46:55,348 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,349 INFO sqlalchemy.engine.base.Engine (503, 'サンティアゴ・デ・コンポステーラ（旧市街）', nan)
2022-05-02 17:46:55,353 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,355 INFO sqlalchemy.engine.base.Engine (504, 'サンティアゴ・デ・コンポステーラの巡礼路：カミノ・フランセスとスペイン北部の道', nan)
2022-05-02 17:46:55,356 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,359 INFO sqlalchemy.engine.base.Engine (505, 'サン・ミリャン・ユソとスソの修道院群', nan)
2022-05-02 17:46:55,359 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,359 INFO sqlalchemy.engine.base.Engine (506, 'セゴビアの旧市街とローマ水道橋', nan)
2022-05-02 17:46:55,362 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,362 INFO sqlalchemy.engine.base.Engine (507, 'セビーリャの大聖堂、アルカサル、インディアス古文書館', nan)
2022-05-02 17:46:55,364 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,365 INFO sqlalchemy.engine.base.Engine (508, 'タラゴナの考古遺跡群', nan)
2022-05-02 17:46:55,365 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,365 INFO sqlalchemy.engine.base.Engine (509, 'テイデ国立公園', nan)
2022-05-02 17:46:55,367 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,368 INFO sqlalchemy.engine.base.Engine (510, 'ドニャーナ国立公園', nan)
2022-05-02 17:46:55,370 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,372 INFO sqlalchemy.engine.base.Engine (511, 'トラムンタナ山脈の文化的景観', nan)
2022-05-02 17:46:55,372 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,374 INFO sqlalchemy.engine.base.Engine (512, 'バルセロナのカタルーニャ音楽堂とサン・パウ病院', nan)
2022-05-02 17:46:55,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,375 INFO sqlalchemy.engine.base.Engine (513, 'バレンシアのラ・ロンハ・デ・ラ・セダ', nan)
2022-05-02 17:46:55,375 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,377 INFO sqlalchemy.engine.base.Engine (514, 'ビスカヤ橋', nan)
2022-05-02 17:46:55,377 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,377 INFO sqlalchemy.engine.base.Engine (515, 'ブルゴスの大聖堂', nan)
2022-05-02 17:46:55,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,378 INFO sqlalchemy.engine.base.Engine (516, 'ヘラクレスの塔', nan)
2022-05-02 17:46:55,378 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,379 INFO sqlalchemy.engine.base.Engine (517, 'ボイ渓谷のカタルーニャ風ロマネスク様式教会群', nan)
2022-05-02 17:46:55,380 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,380 INFO sqlalchemy.engine.base.Engine (518, 'ポブレの修道院', nan)
2022-05-02 17:46:55,381 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,383 INFO sqlalchemy.engine.base.Engine (519, 'マドリードのエル・エスコリアール修道院と王立施設', nan)
2022-05-02 17:46:55,384 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,384 INFO sqlalchemy.engine.base.Engine (520, 'メリダの考古遺跡群', nan)
2022-05-02 17:46:55,386 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,387 INFO sqlalchemy.engine.base.Engine (521, '要塞都市クエンカ', nan)
2022-05-02 17:46:55,388 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,389 INFO sqlalchemy.engine.base.Engine (522, 'ラス・メドゥラス', nan)
2022-05-02 17:46:55,392 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,392 INFO sqlalchemy.engine.base.Engine (523, 'ルーゴのローマの城壁群', nan)
2022-05-02 17:46:55,393 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,393 INFO sqlalchemy.engine.base.Engine (524, '歴史都市トレド', nan)
2022-05-02 17:46:55,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,394 INFO sqlalchemy.engine.base.Engine (529, 'ピレネー山脈のペルデュ山', nan)
2022-05-02 17:46:55,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,394 INFO sqlalchemy.engine.base.Engine (530, 'コア渓谷とシエガ・ベルデの先史時代の岩絵群', nan)
2022-05-02 17:46:55,394 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,395 INFO sqlalchemy.engine.base.Engine (531, '中央スリナム自然保護区', nan)
2022-05-02 17:46:55,395 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,395 INFO sqlalchemy.engine.base.Engine (532, 'パラマリボの歴史街区', nan)
2022-05-02 17:46:55,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,396 INFO sqlalchemy.engine.base.Engine (533, 'ゴールの旧市街とその要塞', nan)
2022-05-02 17:46:55,396 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,396 INFO sqlalchemy.engine.base.Engine (534, 'シーギリヤの古代都市', nan)
2022-05-02 17:46:55,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,397 INFO sqlalchemy.engine.base.Engine (535, 'シンハラジャ森林保護区', nan)
2022-05-02 17:46:55,397 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,397 INFO sqlalchemy.engine.base.Engine (536, 'スリランカ中央高地', nan)
2022-05-02 17:46:55,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,398 INFO sqlalchemy.engine.base.Engine (537, '聖地アヌラーダプラ', nan)
2022-05-02 17:46:55,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,398 INFO sqlalchemy.engine.base.Engine (538, '聖地キャンディ', nan)
2022-05-02 17:46:55,398 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,399 INFO sqlalchemy.engine.base.Engine (539, 'ランギリ・ダンブッラの石窟寺院', nan)
2022-05-02 17:46:55,399 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,399 INFO sqlalchemy.engine.base.Engine (540, 'ポロンナルワの古代都市', nan)
2022-05-02 17:46:55,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,400 INFO sqlalchemy.engine.base.Engine (541, 'ヴルコリニェツの伝統的集落', nan)
2022-05-02 17:46:55,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,400 INFO sqlalchemy.engine.base.Engine (542, 'カルパティア山脈のスロバキア側の木造教会群', nan)
2022-05-02 17:46:55,400 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,401 INFO sqlalchemy.engine.base.Engine (543, 'バルジェヨウ街並保存地区', nan)
2022-05-02 17:46:55,401 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,401 INFO sqlalchemy.engine.base.Engine (545, 'レヴォチャ、スピシュ城と関連する文化的建造物群', nan)
2022-05-02 17:46:55,402 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,402 INFO sqlalchemy.engine.base.Engine (546, 'アグテレク・カルストとスロバキア・カルストの洞窟群', nan)

2022-05-02 17:46:55,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,403 INFO sqlalchemy.engine.base.Engine (547, 'シュコツィアンの洞窟群', nan)
2022-05-02 17:46:55,403 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,403 INFO sqlalchemy.engine.base.Engine (549, 'アルマデンとイドリア－水銀鉱山の遺跡', nan)
2022-05-02 17:46:55,404 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,404 INFO sqlalchemy.engine.base.Engine (550, 'アルダブラ環礁', nan)
2022-05-02 17:46:55,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,405 INFO sqlalchemy.engine.base.Engine (552, 'ゴレ島', nan)
2022-05-02 17:46:55,405 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,405 INFO sqlalchemy.engine.base.Engine (553, 'サルーム・デルタ', nan)
2022-05-02 17:46:55,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,406 INFO sqlalchemy.engine.base.Engine (554, 'サン・ルイ島', nan)
2022-05-02 17:46:55,406 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,406 INFO sqlalchemy.engine.base.Engine (555, 'ジュジ国立鳥類保護区', nan)
2022-05-02 17:46:55,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,407 INFO sqlalchemy.engine.base.Engine (556, 'ニョコロ・コバ国立公園', nan)
2022-05-02 17:46:55,407 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,407 INFO sqlalchemy.engine.base.Engine (558, 'ガレリウス帝の宮殿、ガムジグラード－ロムリアーナ', nan)
2022-05-02 17:46:55,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,408 INFO sqlalchemy.engine.base.Engine (559, 'コソボの中世建造物群', nan)
2022-05-02 17:46:55,408 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,408 INFO sqlalchemy.engine.base.Engine (560, 'スタリ・ラスの遺跡とソポチャニの修道院', nan)
2022-05-02 17:46:55,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,409 INFO sqlalchemy.engine.base.Engine (561, 'ストゥデニツァ修道院', nan)
2022-05-02 17:46:55,409 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,409 INFO sqlalchemy.engine.base.Engine (562, 'ブリムストーン・ヒル要塞国立公園', nan)
2022-05-02 17:46:55,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,410 INFO sqlalchemy.engine.base.Engine (563, 'ピトンズ管理地区', nan)
2022-05-02 17:46:55,410 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,410 INFO sqlalchemy.engine.base.Engine (564, '東レンネル', nan)
2022-05-02 17:46:55,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,411 INFO sqlalchemy.engine.base.Engine (565, 'アユタヤと周辺の歴史地区', nan)
2022-05-02 17:46:55,411 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,411 INFO sqlalchemy.engine.base.Engine (566, 'スコータイと周辺の歴史地区', nan)
2022-05-02 17:46:55,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,412 INFO sqlalchemy.engine.base.Engine (567, 'トゥンヤイ－ファイ・カ・ケン野生生物保護区', nan)
2022-05-02 17:46:55,412 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,412 INFO sqlalchemy.engine.base.Engine (568, 'ドン・パヤーイェン－カオ・ヤイの森林群', nan)
2022-05-02 17:46:55,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,413 INFO sqlalchemy.engine.base.Engine (569, 'バンチェンの考古遺跡', nan)
2022-05-02 17:46:55,413 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,413 INFO sqlalchemy.engine.base.Engine (570, '慶州の歴史地区', nan)
2022-05-02 17:46:55,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,414 INFO sqlalchemy.engine.base.Engine (571, '高敞、和順、江華の支石墓跡', nan)
2022-05-02 17:46:55,414 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,414 INFO sqlalchemy.engine.base.Engine (572, '水原の華城', nan)
2022-05-02 17:46:55,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,415 INFO sqlalchemy.engine.base.Engine (573, '石窟庵と仏国寺', nan)
2022-05-02 17:46:55,415 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,415 INFO sqlalchemy.engine.base.Engine (574, '済州火山島と溶岩洞窟群', nan)
2022-05-02 17:46:55,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,416 INFO sqlalchemy.engine.base.Engine (575, '昌徳宮', nan)
2022-05-02 17:46:55,416 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,416 INFO sqlalchemy.engine.base.Engine (576, '朝鮮王朝の王墓群', nan)
2022-05-02 17:46:55,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,417 INFO sqlalchemy.engine.base.Engine (577, '宗廟', nan)
2022-05-02 17:46:55,417 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,417 INFO sqlalchemy.engine.base.Engine (578, '『八萬大蔵経』版木所蔵の海印寺', nan)
2022-05-02 17:46:55,418 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,418 INFO sqlalchemy.engine.base.Engine (579, '河回村と良洞村の歴史的集落群', nan)
2022-05-02 17:46:55,419 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,419 INFO sqlalchemy.engine.base.Engine (580, '南漢山城（ナムハンサンソン）', nan)
2022-05-02 17:46:55,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,420 INFO sqlalchemy.engine.base.Engine (583, '百済の歴史地区', nan)
2022-05-02 17:46:55,420 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,421 INFO sqlalchemy.engine.base.Engine (586, 'サラズム：原始都市遺跡', nan)
2022-05-02 17:46:55,421 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,422 INFO sqlalchemy.engine.base.Engine (587, 'タジキスタン国立公園（パミールの山脈）', nan)
2022-05-02 17:46:55,422 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,423 INFO sqlalchemy.engine.base.Engine (588, 'キリマンジャロ国立公園', nan)
2022-05-02 17:46:55,423 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,424 INFO sqlalchemy.engine.base.Engine (589, 'キルワ・キシワニとソンゴ・ムナラの遺跡', nan)
2022-05-02 17:46:55,424 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,424 INFO sqlalchemy.engine.base.Engine (591, 'ザンジバル島のストーン・タウン', nan)
2022-05-02 17:46:55,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,425 INFO sqlalchemy.engine.base.Engine (592, 'セルー動物保護区', nan)
2022-05-02 17:46:55,425 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,426 INFO sqlalchemy.engine.base.Engine (593, 'セレンゲティ国立公園', nan)
2022-05-02 17:46:55,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,426 INFO sqlalchemy.engine.base.Engine (595, 'オロモウツの聖三位一体記念柱', nan)
2022-05-02 17:46:55,426 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,427 INFO sqlalchemy.engine.base.Engine (596, 'クトナー・ホラ歴史地区の聖バルボラ教会とセドレツ地区の聖母マリア大聖堂', nan)
2022-05-02 17:46:55,427 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,427 INFO sqlalchemy.engine.base.Engine (597, 'クロムニェジーシュの庭園と宮殿', nan)
2022-05-02 17:46:55,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,428 INFO sqlalchemy.engine.base.Engine (598, 'ゼレナー・ホラにあるネポムークの聖ヨハネ巡礼教会', nan)
2022-05-02 17:46:55,428 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,428 INFO sqlalchemy.engine.base.Engine (599, 'チェスキー・クルムロフの歴史地区', nan)
2022-05-02 17:46:55,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,429 INFO sqlalchemy.engine.base.Engine (600, 'テルチの歴史地区', nan)
2022-05-02 17:46:55,429 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,429 INFO sqlalchemy.engine.base.Engine (601, 'トジェビーチのユダヤ人街とプロコピウス聖堂', nan)
2022-05-02 17:46:55,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,430 INFO sqlalchemy.engine.base.Engine (602, 'プラハの歴史地区', nan)
2022-05-02 17:46:55,430 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,430 INFO sqlalchemy.engine.base.Engine (603, 'ブルノのトゥーゲントハート邸', nan)
2022-05-02 17:46:55,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,431 INFO sqlalchemy.engine.base.Engine (604, 'ホラショヴィツェの歴史的集落', nan)
2022-05-02 17:46:55,431 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,431 INFO sqlalchemy.engine.base.Engine (605, 'リトミシュル城', nan)
2022-05-02 17:46:55,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,432 INFO sqlalchemy.engine.base.Engine (606, 'レドニツェ－ヴァルチツェの文化的景観', nan)
2022-05-02 17:46:55,432 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,432 INFO sqlalchemy.engine.base.Engine (609, 'ウニアンガ湖群', nan)
2022-05-02 17:46:55,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,433 INFO sqlalchemy.engine.base.Engine (612, '安徽省南部の古村落－西逓・宏村', nan)
2022-05-02 17:46:55,433 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,434 INFO sqlalchemy.engine.base.Engine (613, '頤和園：北京の夏の離宮と皇帝庭園', nan)
2022-05-02 17:46:55,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,434 INFO sqlalchemy.engine.base.Engine (614, '殷墟', nan)
2022-05-02 17:46:55,434 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,435 INFO sqlalchemy.engine.base.Engine (615, '雲岡石窟', nan)
2022-05-02 17:46:55,435 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,435 INFO sqlalchemy.engine.base.Engine (616, '雲南保護地域の三江併流群', nan)
2022-05-02 17:46:55,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,436 INFO sqlalchemy.engine.base.Engine (617, '開平の望楼群と村落', nan)
2022-05-02 17:46:55,436 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,436 INFO sqlalchemy.engine.base.Engine (618, '峨眉山と楽山大仏', nan)
2022-05-02 17:46:55,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,437 INFO sqlalchemy.engine.base.Engine (619, '九寨溝：歴史的・景観的重要地区', nan)
2022-05-02 17:46:55,437 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,438 INFO sqlalchemy.engine.base.Engine (620, '曲阜の孔廟、孔林、孔府', nan)
2022-05-02 17:46:55,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,438 INFO sqlalchemy.engine.base.Engine (621, '黄山', nan)
2022-05-02 17:46:55,438 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,439 INFO sqlalchemy.engine.base.Engine (622, '杭州にある西湖の文化的景観', nan)
2022-05-02 17:46:55,439 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,439 INFO sqlalchemy.engine.base.Engine (623, '黄龍：歴史的・景観的重要地区', nan)
2022-05-02 17:46:55,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,440 INFO sqlalchemy.engine.base.Engine (624, '古代高句麗王国の都城と古墳群', nan)
2022-05-02 17:46:55,440 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,440 INFO sqlalchemy.engine.base.Engine (625, '五台山', nan)
2022-05-02 17:46:55,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,441 INFO sqlalchemy.engine.base.Engine (626, '三清山国立公園', nan)
2022-05-02 17:46:55,441 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,441 INFO sqlalchemy.engine.base.Engine (627, '始皇帝陵と兵馬俑坑', nan)
2022-05-02 17:46:55,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,442 INFO sqlalchemy.engine.base.Engine (628, '四川省のジャイアントパンダ保護区群', nan)
2022-05-02 17:46:55,442 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,442 INFO sqlalchemy.engine.base.Engine (629, '承徳の避暑山荘と外八廟', nan)
2022-05-02 17:46:55,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,443 INFO sqlalchemy.engine.base.Engine (630, '青城山と都江堰水利施設', nan)
2022-05-02 17:46:55,443 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,443 INFO sqlalchemy.engine.base.Engine (631, '蘇州の園林', nan)
2022-05-02 17:46:55,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,444 INFO sqlalchemy.engine.base.Engine (632, '泰山', nan)
2022-05-02 17:46:55,444 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,445 INFO sqlalchemy.engine.base.Engine (633, '大足石刻', nan)
2022-05-02 17:46:55,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,445 INFO sqlalchemy.engine.base.Engine (634, '中国南部のカルスト地帯', nan)
2022-05-02 17:46:55,445 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,445 INFO sqlalchemy.engine.base.Engine (635, '中国の丹霞地形', nan)
2022-05-02 17:46:55,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,446 INFO sqlalchemy.engine.base.Engine (636, '天壇：北京の皇帝祭壇', nan)
2022-05-02 17:46:55,446 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,446 INFO sqlalchemy.engine.base.Engine (637, '登封の歴史的建造物群－天地之中', nan)
2022-05-02 17:46:55,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,447 INFO sqlalchemy.engine.base.Engine (638, '敦煌の莫高窟', nan)
2022-05-02 17:46:55,447 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,447 INFO sqlalchemy.engine.base.Engine (640, '武夷山', nan)
2022-05-02 17:46:55,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,448 INFO sqlalchemy.engine.base.Engine (641, '福建土楼群', nan)
2022-05-02 17:46:55,448 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,448 INFO sqlalchemy.engine.base.Engine (642, '武当山の道教寺院群', nan)
2022-05-02 17:46:55,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,449 INFO sqlalchemy.engine.base.Engine (643, '武陵源：歴史的・景観的重要地区', nan)
2022-05-02 17:46:55,449 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,449 INFO sqlalchemy.engine.base.Engine (644, '平遥の古代都市', nan)
2022-05-02 17:46:55,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,450 INFO sqlalchemy.engine.base.Engine (645, '北京原人化石出土の周口店遺跡', nan)
2022-05-02 17:46:55,450 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,450 INFO sqlalchemy.engine.base.Engine (646, '北京と瀋陽の故宮', nan)
2022-05-02 17:46:55,451 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,451 INFO sqlalchemy.engine.base.Engine (647, 'マカオの歴史地区', nan)
2022-05-02 17:46:55,452 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,452 INFO sqlalchemy.engine.base.Engine (648, '明・清時代の皇帝陵墓', nan)
2022-05-02 17:46:55,453 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,454 INFO sqlalchemy.engine.base.Engine (650, '龍門石窟', nan)
2022-05-02 17:46:55,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,455 INFO sqlalchemy.engine.base.Engine (651, '麗江の旧市街', nan)
2022-05-02 17:46:55,455 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,456 INFO sqlalchemy.engine.base.Engine (652, '廬山国立公園', nan)
2022-05-02 17:46:55,456 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,456 INFO sqlalchemy.engine.base.Engine (653, '元の上都遺跡', nan)
2022-05-02 17:46:55,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,457 INFO sqlalchemy.engine.base.Engine (654, '澄江の化石出土地域', nan)
2022-05-02 17:46:55,457 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,457 INFO sqlalchemy.engine.base.Engine (655, '紅河ハニ族棚田群の文化的景観', nan)
2022-05-02 17:46:55,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,458 INFO sqlalchemy.engine.base.Engine (656, '新疆天山', nan)
2022-05-02 17:46:55,458 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,458 INFO sqlalchemy.engine.base.Engine (657, '京杭大運河', nan)
2022-05-02 17:46:55,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,459 INFO sqlalchemy.engine.base.Engine (661, '土司の遺跡群', nan)
2022-05-02 17:46:55,459 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,460 INFO sqlalchemy.engine.base.Engine (667, 'シルク・ロード：長安から天山回廊の交易網', nan)
2022-05-02 17:46:55,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,460 INFO sqlalchemy.engine.base.Engine (668, 'イシュケル国立公園', nan)
2022-05-02 17:46:55,460 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,461 INFO sqlalchemy.engine.base.Engine (669, 'エル・ジェムの円形闘技場', nan)
2022-05-02 17:46:55,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,461 INFO sqlalchemy.engine.base.Engine (672, 'スースの旧市街', nan)
2022-05-02 17:46:55,461 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,462 INFO sqlalchemy.engine.base.Engine (674, 'チュニスの旧市街', nan)
2022-05-02 17:46:55,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,462 INFO sqlalchemy.engine.base.Engine (676, '海港都市バルパライソの歴史地区', nan)
2022-05-02 17:46:55,462 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,463 INFO sqlalchemy.engine.base.Engine (677, 'セウェル鉱山都市', nan)
2022-05-02 17:46:55,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,463 INFO sqlalchemy.engine.base.Engine (678, 'チロエの教会堂群', nan)
2022-05-02 17:46:55,463 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,464 INFO sqlalchemy.engine.base.Engine (679, 'ハンバーストーンとサンタ・ラウラの硝石工場群', nan)
2022-05-02 17:46:55,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,464 INFO sqlalchemy.engine.base.Engine (680, 'ラパ・ニュイ国立公園', nan)
2022-05-02 17:46:55,464 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,464 INFO sqlalchemy.engine.base.Engine (683, 'ワッデン海', nan)
2022-05-02 17:46:55,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,465 INFO sqlalchemy.engine.base.Engine (684, 'イェリング墳墓、ルーン石碑と教会', nan)
2022-05-02 17:46:55,465 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,465 INFO sqlalchemy.engine.base.Engine (685, 'イルリサット・アイスフィヨルド', nan)
2022-05-02 17:46:55,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,466 INFO sqlalchemy.engine.base.Engine (686, 'クロンボー城', nan)
2022-05-02 17:46:55,466 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,466 INFO sqlalchemy.engine.base.Engine (687, 'ロスキレの大聖堂', nan)
2022-05-02 17:46:55,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,467 INFO sqlalchemy.engine.base.Engine (688, 'ステウンスの崖壁', nan)
2022-05-02 17:46:55,467 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,467 INFO sqlalchemy.engine.base.Engine (689, 'クリスティアンスフェル：モラヴィア教会入植地', nan)
2022-05-02 17:46:55,468 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,468 INFO sqlalchemy.engine.base.Engine (690, 'シェラン島北部の王室狩猟場の景観', nan)
2022-05-02 17:46:55,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,469 INFO sqlalchemy.engine.base.Engine (694, 'アーヘンの大聖堂', nan)
2022-05-02 17:46:55,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,469 INFO sqlalchemy.engine.base.Engine (695, 'アールフェルトのファーグス靴型工場', nan)
2022-05-02 17:46:55,469 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,470 INFO sqlalchemy.engine.base.Engine (696, 'アイスレーベンとヴィッテンベルクのルター記念建造物群', nan)
2022-05-02 17:46:55,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,470 INFO sqlalchemy.engine.base.Engine (697, 'ヴァイマール古典主義文化', nan)
2022-05-02 17:46:55,470 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,471 INFO sqlalchemy.engine.base.Engine (698, 'バウハウス関連遺産群：ヴァイマールとデッサウ、ベルナウ', nan)
2022-05-02 17:46:55,471 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,471 INFO sqlalchemy.engine.base.Engine (700, 'ヴィースの巡礼教会', nan)
2022-05-02 17:46:55,472 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,472 INFO sqlalchemy.engine.base.Engine (701, 'ヴュルツブルクの司教館と庭園群', nan)
2022-05-02 17:46:55,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,473 INFO sqlalchemy.engine.base.Engine (702, 'エッセンのツォルフェライン炭鉱業遺産群', nan)
2022-05-02 17:46:55,473 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,473 INFO sqlalchemy.engine.base.Engine (703, 'クヴェートリンブルクの旧市街と聖堂参事会教会、城', nan)
2022-05-02 17:46:55,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,474 INFO sqlalchemy.engine.base.Engine (704, 'ケルンの大聖堂', nan)
2022-05-02 17:46:55,474 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,474 INFO sqlalchemy.engine.base.Engine (705, '修道院の島ライヒェナウ', nan)
2022-05-02 17:46:55,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,475 INFO sqlalchemy.engine.base.Engine (706, 'シュトラールズントおよびヴィスマールの歴史地区', nan)
2022-05-02 17:46:55,475 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,475 INFO sqlalchemy.engine.base.Engine (707, 'シュパイアの大聖堂', nan)
2022-05-02 17:46:55,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,476 INFO sqlalchemy.engine.base.Engine (708, 'デッサウ・ヴェルリッツの庭園王国', nan)
2022-05-02 17:46:55,476 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,476 INFO sqlalchemy.engine.base.Engine (709, 'トリーアのローマ遺跡、聖ペトロ大聖堂と聖母聖堂', nan)
2022-05-02 17:46:55,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,477 INFO sqlalchemy.engine.base.Engine (710, 'ハンザ都市リューベック', nan)
2022-05-02 17:46:55,477 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,477 INFO sqlalchemy.engine.base.Engine (711, 'バンベルクの旧市街', nan)
2022-05-02 17:46:55,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,478 INFO sqlalchemy.engine.base.Engine (712, 'ヒルデスハイムの聖マリア大聖堂と聖ミヒャエル聖堂', nan)
2022-05-02 17:46:55,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,478 INFO sqlalchemy.engine.base.Engine (713, 'フェルクリンゲンの製鉄所', nan)
2022-05-02 17:46:55,478 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,479 INFO sqlalchemy.engine.base.Engine (714, 'ブリュールのアウグストゥスブルク城と別邸ファルケンルスト', nan)
2022-05-02 17:46:55,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,479 INFO sqlalchemy.engine.base.Engine (715, 'ブレーメンのマルクト広場にある市庁舎とローラント像', nan)
2022-05-02 17:46:55,479 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,480 INFO sqlalchemy.engine.base.Engine (716, 'ベルリンのムゼウムスインゼル（博物館島）', nan)
2022-05-02 17:46:55,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,480 INFO sqlalchemy.engine.base.Engine (717, 'ベルリンのモダニズム公共住宅', nan)
2022-05-02 17:46:55,480 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,480 INFO sqlalchemy.engine.base.Engine (718, 'ポツダムとベルリンの宮殿と庭園', nan)
2022-05-02 17:46:55,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,481 INFO sqlalchemy.engine.base.Engine (719, 'マウルブロンの修道院関連建造物群', nan)
2022-05-02 17:46:55,481 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,482 INFO sqlalchemy.engine.base.Engine (720, 'メッセルの化石採掘地区', nan)
2022-05-02 17:46:55,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,482 INFO sqlalchemy.engine.base.Engine (721, 'ライン渓谷中流上部', nan)
2022-05-02 17:46:55,482 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,483 INFO sqlalchemy.engine.base.Engine (722, 'ランメルスベルク鉱山とゴスラーの歴史地区、ハルツ山地上部の水利システム', nan)
2022-05-02 17:46:55,483 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,483 INFO sqlalchemy.engine.base.Engine (723, 'レーゲンスブルク旧市街とシュタットアムホーフ', nan)
2022-05-02 17:46:55,484 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,484 INFO sqlalchemy.engine.base.Engine (724, 'ロルシュの修道院遺跡', nan)
2022-05-02 17:46:55,485 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,485 INFO sqlalchemy.engine.base.Engine (725, 'バイロイトの辺境伯オペラハウス', nan)
2022-05-02 17:46:55,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,486 INFO sqlalchemy.engine.base.Engine (726, 'ヴィルヘルムスヘーエ丘陵公園', nan)
2022-05-02 17:46:55,486 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,486 INFO sqlalchemy.engine.base.Engine (727, 'コルヴァイの修道院に残るカロリング朝時代の西構えと修道院都市遺構', nan)
2022-05-02 17:46:55,487 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,488 INFO sqlalchemy.engine.base.Engine (728, 'シュパイヒャーシュタットと、チリハウスのあるコントールハウス地区', nan)
2022-05-02 17:46:55,489 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,489 INFO sqlalchemy.engine.base.Engine (735, 'クタマク：バタマリバ人の土地', nan)
2022-05-02 17:46:55,490 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,490 INFO sqlalchemy.engine.base.Engine (736, '植民都市サント・ドミンゴ', nan)
2022-05-02 17:46:55,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,491 INFO sqlalchemy.engine.base.Engine (737, 'モルヌ・トロワ・ピトン国立公園', nan)
2022-05-02 17:46:55,491 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,491 INFO sqlalchemy.engine.base.Engine (738, 'クフナ ‐ ウルゲンチ', nan)
2022-05-02 17:46:55,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,492 INFO sqlalchemy.engine.base.Engine (739, '国立歴史文化公園“メルヴ”', nan)
2022-05-02 17:46:55,492 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,493 INFO sqlalchemy.engine.base.Engine (740, 'ニサのパルティア王国の要塞', nan)
2022-05-02 17:46:55,493 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,493 INFO sqlalchemy.engine.base.Engine (741, 'イスタンブルの歴史地区', nan)
2022-05-02 17:46:55,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,494 INFO sqlalchemy.engine.base.Engine (742, 'エディルネのセリミエ・モスクとその関連施設', nan)
2022-05-02 17:46:55,494 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,494 INFO sqlalchemy.engine.base.Engine (744, 'クサントスとレトーン', nan)
2022-05-02 17:46:55,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,495 INFO sqlalchemy.engine.base.Engine (745, 'サフランボルの旧市街', nan)
2022-05-02 17:46:55,495 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,496 INFO sqlalchemy.engine.base.Engine (746, 'ディヴリーイの大モスクと病院', nan)
2022-05-02 17:46:55,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,496 INFO sqlalchemy.engine.base.Engine (747, 'トロイアの考古遺跡', nan)
2022-05-02 17:46:55,496 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,497 INFO sqlalchemy.engine.base.Engine (748, 'ネムルト・ダーの巨大墳墓', nan)
2022-05-02 17:46:55,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,497 INFO sqlalchemy.engine.base.Engine (749, 'ヒエラポリスとパムッカレ', nan)
2022-05-02 17:46:55,497 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,498 INFO sqlalchemy.engine.base.Engine (750, 'ヒッタイトの首都ハットゥシャ', nan)
2022-05-02 17:46:55,498 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,498 INFO sqlalchemy.engine.base.Engine (751, 'チャタルヒュユクの新石器時代の遺跡', nan)
2022-05-02 17:46:55,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,499 INFO sqlalchemy.engine.base.Engine (752, 'ブルサとジュマルクズク：オスマン帝国発祥の地', nan)
2022-05-02 17:46:55,499 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,499 INFO sqlalchemy.engine.base.Engine (753, 'ペルガモンとその周辺：様々な時代からなる文化的景観', nan)
2022-05-02 17:46:55,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,500 INFO sqlalchemy.engine.base.Engine (754, 'ディヤルバクル要塞とヘヴセル庭園群の文化的景観', nan)
2022-05-02 17:46:55,500 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,500 INFO sqlalchemy.engine.base.Engine (755, 'エフェソス', nan)
2022-05-02 17:46:55,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,501 INFO sqlalchemy.engine.base.Engine (760, 'オスン－オソボの聖林', nan)
2022-05-02 17:46:55,501 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,502 INFO sqlalchemy.engine.base.Engine (761, 'スクルの文化的景観', nan)
2022-05-02 17:46:55,502 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,503 INFO sqlalchemy.engine.base.Engine (763, 'ナミブ砂漠', nan)
2022-05-02 17:46:55,503 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,503 INFO sqlalchemy.engine.base.Engine (764, 'レオン・ビエホの遺跡群', nan)
2022-05-02 17:46:55,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,504 INFO sqlalchemy.engine.base.Engine (765, 'レオン大聖堂', nan)
2022-05-02 17:46:55,504 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,505 INFO sqlalchemy.engine.base.Engine (767, 'アガデスの歴史地区', nan)
2022-05-02 17:46:55,505 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,505 INFO sqlalchemy.engine.base.Engine (769, '厳島神社', nan)
2022-05-02 17:46:55,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,506 INFO sqlalchemy.engine.base.Engine (770, '石見銀山遺跡とその文化的景観', nan)
2022-05-02 17:46:55,506 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,507 INFO sqlalchemy.engine.base.Engine (771, '小笠原諸島', nan)
2022-05-02 17:46:55,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,507 INFO sqlalchemy.engine.base.Engine (772, '紀伊山地の霊場と参詣道', nan)
2022-05-02 17:46:55,507 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,508 INFO sqlalchemy.engine.base.Engine (773, '古都京都の文化財', nan)
2022-05-02 17:46:55,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,508 INFO sqlalchemy.engine.base.Engine (774, '古都奈良の文化財', nan)
2022-05-02 17:46:55,508 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,509 INFO sqlalchemy.engine.base.Engine (775, '白神山地', nan)
2022-05-02 17:46:55,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,509 INFO sqlalchemy.engine.base.Engine (776, '白川郷・五箇山の合掌造り集落', nan)
2022-05-02 17:46:55,509 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,510 INFO sqlalchemy.engine.base.Engine (777, '知床', nan)
2022-05-02 17:46:55,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,510 INFO sqlalchemy.engine.base.Engine (778, '日光の社寺', nan)
2022-05-02 17:46:55,510 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,511 INFO sqlalchemy.engine.base.Engine (779, '姫路城', nan)
2022-05-02 17:46:55,511 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,511 INFO sqlalchemy.engine.base.Engine (780, '平泉－仏国土（浄土）を表す建築・庭園及び考古学的遺跡群－', nan)
2022-05-02 17:46:55,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,512 INFO sqlalchemy.engine.base.Engine (781, '広島平和記念碑（原爆ドーム）', nan)
2022-05-02 17:46:55,512 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,512 INFO sqlalchemy.engine.base.Engine (782, '法隆寺地域の仏教建造物群', nan)
2022-05-02 17:46:55,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,513 INFO sqlalchemy.engine.base.Engine (783, '屋久島', nan)
2022-05-02 17:46:55,513 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,513 INFO sqlalchemy.engine.base.Engine (784, '琉球王国のグスク及び関連遺産群', nan)
2022-05-02 17:46:55,519 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,520 INFO sqlalchemy.engine.base.Engine (785, '富士山─信仰の対象と芸術の源泉', nan)
2022-05-02 17:46:55,520 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,521 INFO sqlalchemy.engine.base.Engine (786, '富岡製糸場と絹産業遺産群', nan)
2022-05-02 17:46:55,521 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,522 INFO sqlalchemy.engine.base.Engine (787, '明治日本の産業革命遺産\u3000製鉄・製鋼、造船、石炭産業', nan)
2022-05-02 17:46:55,523 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,523 INFO sqlalchemy.engine.base.Engine (788, '「神宿る島」宗像・沖ノ島と関連遺産群', nan)
2022-05-02 17:46:55,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,524 INFO sqlalchemy.engine.base.Engine (789, '長崎と天草地方の潜伏キリシタン関連遺産', nan)
2022-05-02 17:46:55,524 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,525 INFO sqlalchemy.engine.base.Engine (790, '百舌鳥・古市古墳群', nan)
2022-05-02 17:46:55,525 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,526 INFO sqlalchemy.engine.base.Engine (791, '北海道・北東北の縄文遺跡群', nan)
2022-05-02 17:46:55,526 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,526 INFO sqlalchemy.engine.base.Engine (792, '奄美大島、徳之島、沖縄島北部及び西表島', nan)
2022-05-02 17:46:55,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,527 INFO sqlalchemy.engine.base.Engine (793, 'テ・ワヒポウナム', nan)
2022-05-02 17:46:55,527 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,528 INFO sqlalchemy.engine.base.Engine (794, 'トンガリロ国立公園', nan)
2022-05-02 17:46:55,528 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,528 INFO sqlalchemy.engine.base.Engine (795, 'ニュージーランドの亜南極諸島', nan)
2022-05-02 17:46:55,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,529 INFO sqlalchemy.engine.base.Engine (796, 'カトマンズの谷', nan)
2022-05-02 17:46:55,529 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,530 INFO sqlalchemy.engine.base.Engine (798, 'チトワン国立公園', nan)
2022-05-02 17:46:55,532 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,532 INFO sqlalchemy.engine.base.Engine (799, '仏陀の生誕地ルンビニー', nan)
2022-05-02 17:46:55,533 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,533 INFO sqlalchemy.engine.base.Engine (800, 'アルタの岩絵群', nan)
2022-05-02 17:46:55,534 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,535 INFO sqlalchemy.engine.base.Engine (801, 'ヴェガエイヤン：ヴェガ群島', nan)
2022-05-02 17:46:55,536 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,537 INFO sqlalchemy.engine.base.Engine (802, 'ウルネスの木造教会', nan)
2022-05-02 17:46:55,537 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,537 INFO sqlalchemy.engine.base.Engine (803, 'ノルウェー西部のフィヨルド、ガイランゲルフィヨルドとネーロイフィヨルド', nan)
2022-05-02 17:46:55,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,538 INFO sqlalchemy.engine.base.Engine (804, 'ベルゲンのブリッゲン地区', nan)
2022-05-02 17:46:55,538 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,539 INFO sqlalchemy.engine.base.Engine (805, 'レーロースの鉱山都市と周辺', nan)
2022-05-02 17:46:55,539 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,539 INFO sqlalchemy.engine.base.Engine (806, 'リューカン・ノトッデンの産業遺産', nan)
2022-05-02 17:46:55,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,540 INFO sqlalchemy.engine.base.Engine (807, 'カルアトル・バーレーン：古代の港とディルムンの都', nan)
2022-05-02 17:46:55,540 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,540 INFO sqlalchemy.engine.base.Engine (808, 'ペルシャ湾の真珠産業関連遺産：島嶼経済の証拠', nan)
2022-05-02 17:46:55,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,541 INFO sqlalchemy.engine.base.Engine (810, 'ハイチの国立歴史公園：シタデル、サン・スーシ宮、ラミエ地区', nan)
2022-05-02 17:46:55,541 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,542 INFO sqlalchemy.engine.base.Engine (812, 'タッタとマクリの歴史的建造物群', nan)
2022-05-02 17:46:55,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,542 INFO sqlalchemy.engine.base.Engine (815, 'ラホール城とシャーラマール庭園', nan)
2022-05-02 17:46:55,542 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,543 INFO sqlalchemy.engine.base.Engine (817, 'コイバ国立公園と特別海洋保護区', nan)
2022-05-02 17:46:55,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,543 INFO sqlalchemy.engine.base.Engine (818, 'ダリエン国立公園', nan)
2022-05-02 17:46:55,543 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,544 INFO sqlalchemy.engine.base.Engine (819, 'パナマ・ビエホ考古遺跡とパナマの歴史地区', nan)
2022-05-02 17:46:55,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,544 INFO sqlalchemy.engine.base.Engine (820, 'パナマのカリブ海側の要塞群：ポルトベロとサン・ロレンツォ', nan)
2022-05-02 17:46:55,544 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,545 INFO sqlalchemy.engine.base.Engine (821, '首長ロイ・マタの旧所領', nan)
2022-05-02 17:46:55,545 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,545 INFO sqlalchemy.engine.base.Engine (822, 'ククの古代農耕遺跡', nan)
2022-05-02 17:46:55,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,546 INFO sqlalchemy.engine.base.Engine (823, 'ロック・アイランドの南部ラグーン', nan)
2022-05-02 17:46:55,546 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,546 INFO sqlalchemy.engine.base.Engine (824, 'パラナ川沿いのイエズス会布教施設群：ラ・サンティシマ・トリニダ・デ・パラナとヘスス・デ・タバランゲ', nan)
2022-05-02 17:46:55,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,547 INFO sqlalchemy.engine.base.Engine (825, '歴史都市ブリッジタウンとその要塞', nan)
2022-05-02 17:46:55,547 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,547 INFO sqlalchemy.engine.base.Engine (826, 'イエス生誕の地：ベツレヘムの聖誕教会と巡礼路', nan)
2022-05-02 17:46:55,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,548 INFO sqlalchemy.engine.base.Engine (827, 'オリーヴとワインの土地－バッティールの丘：南エルサレムの文化的景観', nan)
2022-05-02 17:46:55,548 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,604 INFO sqlalchemy.engine.base.Engine (829, 'トカイ地方のワイン産地の歴史的文化的景観', nan)
2022-05-02 17:46:55,605 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,605 INFO sqlalchemy.engine.base.Engine (830, 'パンノンハルマの千年の歴史をもつベネディクト会修道院と周辺の自然環境', nan)
2022-05-02 17:46:55,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,606 INFO sqlalchemy.engine.base.Engine (831, 'ブダペスト：ドナウ河岸とブダ城地区、アンドラーシ通り', nan)

2022-05-02 17:46:55,606 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,606 INFO sqlalchemy.engine.base.Engine (832, 'ペーチ（ソピアナエ）の初期キリスト教墓所', nan)
2022-05-02 17:46:55,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,607 INFO sqlalchemy.engine.base.Engine (833, 'ホルトバージ国立公園：プスタ（大平原）', nan)
2022-05-02 17:46:55,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,607 INFO sqlalchemy.engine.base.Engine (834, 'ホローケーの伝統的集落', nan)
2022-05-02 17:46:55,607 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,608 INFO sqlalchemy.engine.base.Engine (835, 'シュンドルボン', nan)
2022-05-02 17:46:55,608 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,608 INFO sqlalchemy.engine.base.Engine (836, 'バゲルハット：モスクを中心とした歴史都市', nan)
2022-05-02 17:46:55,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,609 INFO sqlalchemy.engine.base.Engine (837, 'パハルプールの仏教遺跡', nan)
2022-05-02 17:46:55,609 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,609 INFO sqlalchemy.engine.base.Engine (838, 'レブカ歴史的港湾都市', nan)
2022-05-02 17:46:55,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,610 INFO sqlalchemy.engine.base.Engine (839, 'フィリピンのコルディリェーラの棚田群', nan)
2022-05-02 17:46:55,610 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,610 INFO sqlalchemy.engine.base.Engine (845, 'ヴェルラの砕木パルプ・板紙工場', nan)
2022-05-02 17:46:55,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,611 INFO sqlalchemy.engine.base.Engine (846, 'スオメンリンナ要塞', nan)
2022-05-02 17:46:55,611 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,612 INFO sqlalchemy.engine.base.Engine (847, '青銅器時代のサンマルラハデンマキ墓群', nan)
2022-05-02 17:46:55,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,612 INFO sqlalchemy.engine.base.Engine (848, 'ペタヤヴェシの古教会', nan)
2022-05-02 17:46:55,612 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,613 INFO sqlalchemy.engine.base.Engine (849, 'ラウマの旧市街', nan)
2022-05-02 17:46:55,613 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,613 INFO sqlalchemy.engine.base.Engine (851, 'オウロ・プレトの歴史都市', nan)
2022-05-02 17:46:55,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,614 INFO sqlalchemy.engine.base.Engine (852, 'オリンダの歴史地区', nan)
2022-05-02 17:46:55,614 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,614 INFO sqlalchemy.engine.base.Engine (853, 'ゴイアスの歴史地区', nan)
2022-05-02 17:46:55,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,615 INFO sqlalchemy.engine.base.Engine (854, 'コンゴーニャスのボン・ジェズス聖域', nan)
2022-05-02 17:46:55,615 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,616 INFO sqlalchemy.engine.base.Engine (855, 'サルヴァドル・デ・バイアの歴史地区', nan)
2022-05-02 17:46:55,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,616 INFO sqlalchemy.engine.base.Engine (856, 'サン・クリストヴァンのサン・フランシスコ広場', nan)
2022-05-02 17:46:55,616 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,617 INFO sqlalchemy.engine.base.Engine (857, 'サン・ルイスの歴史地区', nan)
2022-05-02 17:46:55,617 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,617 INFO sqlalchemy.engine.base.Engine (858, 'セラ・ダ・カピバラ国立公園', nan)
2022-05-02 17:46:55,618 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,618 INFO sqlalchemy.engine.base.Engine (859, 'セラード自然保護地域群：ヴェアデイロス平原国立公園とエマス国立公園', nan)
2022-05-02 17:46:55,619 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,619 INFO sqlalchemy.engine.base.Engine (860, 'サウス・イースト大西洋沿岸森林保護区群', nan)
2022-05-02 17:46:55,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,620 INFO sqlalchemy.engine.base.Engine (861, 'ディスカヴァリー・コースト大西洋沿岸森林保護区群', nan)
2022-05-02 17:46:55,620 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,621 INFO sqlalchemy.engine.base.Engine (862, '中央アマゾン自然保護区群', nan)
2022-05-02 17:46:55,621 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,622 INFO sqlalchemy.engine.base.Engine (863, 'ディアマンティーナの歴史地区', nan)
2022-05-02 17:46:55,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,623 INFO sqlalchemy.engine.base.Engine (864, 'パンタナル自然保護区', nan)
2022-05-02 17:46:55,623 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,624 INFO sqlalchemy.engine.base.Engine (865, 'ブラジリア', nan)
2022-05-02 17:46:55,624 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,624 INFO sqlalchemy.engine.base.Engine (866, 'ブラジル沖の大西洋の島々：フェルナンド・デ・ノローニャとロカス環礁の保護区群', nan)
2022-05-02 17:46:55,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,625 INFO sqlalchemy.engine.base.Engine (868, 'リオ・デ・ジャネイロ：山と海に囲まれたカリオカの景観', nan)
2022-05-02 17:46:55,625 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,626 INFO sqlalchemy.engine.base.Engine (872, 'ノール＝パ・ドゥ・カレの鉱山地帯', nan)
2022-05-02 17:46:55,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,626 INFO sqlalchemy.engine.base.Engine (874, 'アヴィニョンの歴史地区：教皇庁宮殿、司教の建造物群、アヴィニョンの橋', nan)
2022-05-02 17:46:55,626 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,627 INFO sqlalchemy.engine.base.Engine (875, 'アミアンの大聖堂', nan)
2022-05-02 17:46:55,627 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,627 INFO sqlalchemy.engine.base.Engine (876, 'アルルのローマ遺跡とロマネスク建築', nan)
2022-05-02 17:46:55,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,628 INFO sqlalchemy.engine.base.Engine (877, 'ヴェズレーの教会と丘', nan)
2022-05-02 17:46:55,628 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,629 INFO sqlalchemy.engine.base.Engine (878, 'ヴェゼール渓谷の装飾洞窟と先史遺跡', nan)
2022-05-02 17:46:55,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,629 INFO sqlalchemy.engine.base.Engine (879, 'ヴェルサイユ宮殿と庭園', nan)
2022-05-02 17:46:55,629 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,630 INFO sqlalchemy.engine.base.Engine (880, 'ヴォーバンによる要塞建築群', nan)

2022-05-02 17:46:55,630 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,630 INFO sqlalchemy.engine.base.Engine (881, 'ル・アーヴル：オーギュスト・ペレにより再建された街', nan)
2022-05-02 17:46:55,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,631 INFO sqlalchemy.engine.base.Engine (882, 'オランジュの凱旋門、ローマ劇場とその周辺', nan)
2022-05-02 17:46:55,631 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,631 INFO sqlalchemy.engine.base.Engine (883, 'カルカッソンヌの歴史的城塞都市', nan)
2022-05-02 17:46:55,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,632 INFO sqlalchemy.engine.base.Engine (884, 'コースとセヴェンヌ：地中海性農業牧草地の文化的景観', nan)
2022-05-02 17:46:55,632 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,632 INFO sqlalchemy.engine.base.Engine (885, 'サラン・レ・バン大製塩所からアルケ・スナン王立製塩所までの天日塩生産所', nan)
2022-05-02 17:46:55,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,633 INFO sqlalchemy.engine.base.Engine (886, 'サン・サヴァン・シュール・ガルタンプの修道院教会', nan)
2022-05-02 17:46:55,633 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,633 INFO sqlalchemy.engine.base.Engine (887, 'サン・テミリオン地域', nan)
2022-05-02 17:46:55,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,634 INFO sqlalchemy.engine.base.Engine (888, '司教座都市アルビ', nan)
2022-05-02 17:46:55,634 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,635 INFO sqlalchemy.engine.base.Engine (889, 'シャルトルの大聖堂', nan)
2022-05-02 17:46:55,635 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,635 INFO sqlalchemy.engine.base.Engine (890, 'ストラスブール：グラン・ディルからヌースタットのヨーロッパの都市景観', nan)
2022-05-02 17:46:55,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,636 INFO sqlalchemy.engine.base.Engine (891, '中世市場都市プロヴァン', nan)
2022-05-02 17:46:55,636 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,637 INFO sqlalchemy.engine.base.Engine (892, 'ナンシーのスタニスラス広場、カリエール広場、アリアンス広場', nan)
2022-05-02 17:46:55,637 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,637 INFO sqlalchemy.engine.base.Engine (893, 'ニューカレドニアの珊瑚礁：環礁の多様性と関連する生態系', nan)
2022-05-02 17:46:55,638 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,638 INFO sqlalchemy.engine.base.Engine (894, 'パリのセーヌ河岸', nan)
2022-05-02 17:46:55,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,639 INFO sqlalchemy.engine.base.Engine (895, 'ブールジュの大聖堂', nan)
2022-05-02 17:46:55,639 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,639 INFO sqlalchemy.engine.base.Engine (896, 'フォンテーヌブロー宮殿と庭園', nan)
2022-05-02 17:46:55,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,640 INFO sqlalchemy.engine.base.Engine (897, 'フォントネーのシトー会修道院', nan)
2022-05-02 17:46:55,640 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,640 INFO sqlalchemy.engine.base.Engine (898, 'フランスのサンティアゴ・デ・コンポステーラの巡礼路', nan)
2022-05-02 17:46:55,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,641 INFO sqlalchemy.engine.base.Engine (899, 'ボルドー、月の港', nan)
2022-05-02 17:46:55,641 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,642 INFO sqlalchemy.engine.base.Engine (900, 'ポルト湾：ピアナのカランケ、ジロラッタ湾、スカンドラ保護区', nan)
2022-05-02 17:46:55,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,642 INFO sqlalchemy.engine.base.Engine (901, 'ポン・デュ・ガール（ローマの水道橋）', nan)
2022-05-02 17:46:55,642 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,643 INFO sqlalchemy.engine.base.Engine (902, 'ミディ運河', nan)
2022-05-02 17:46:55,643 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,643 INFO sqlalchemy.engine.base.Engine (904, 'ランスのノートル・ダム大聖堂、サン・レミ旧修道院、トー宮', nan)
2022-05-02 17:46:55,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,644 INFO sqlalchemy.engine.base.Engine (905, 'リヨンの歴史地区', nan)
2022-05-02 17:46:55,644 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,644 INFO sqlalchemy.engine.base.Engine (906, 'レユニオン島：峻峰と圏谷、その外縁', nan)
2022-05-02 17:46:55,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,645 INFO sqlalchemy.engine.base.Engine (907, 'ロワール渓谷：シュリー・シュル・ロワールからシャロンヌまで', nan)
2022-05-02 17:46:55,645 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,645 INFO sqlalchemy.engine.base.Engine (908, 'アルデシュ県ポン・ダルクの装飾洞窟：ショーヴェ・ポン・ダルク洞窟', nan)
2022-05-02 17:46:55,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,646 INFO sqlalchemy.engine.base.Engine (909, 'ブルゴーニュのブドウ栽培の景観', nan)
2022-05-02 17:46:55,646 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,647 INFO sqlalchemy.engine.base.Engine (910, 'シャンパーニュの丘陵、醸造所と貯蔵庫', nan)
2022-05-02 17:46:55,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,647 INFO sqlalchemy.engine.base.Engine (916, 'ベルギーとフランスの鐘楼群', nan)
2022-05-02 17:46:55,647 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,648 INFO sqlalchemy.engine.base.Engine (917, 'イワノヴォの岩窟教会群', nan)
2022-05-02 17:46:55,648 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,648 INFO sqlalchemy.engine.base.Engine (918, 'カザンラクのトラキア人の古墳', nan)
2022-05-02 17:46:55,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,649 INFO sqlalchemy.engine.base.Engine (919, 'スヴェシュタリのトラキア人の古墳', nan)
2022-05-02 17:46:55,649 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,649 INFO sqlalchemy.engine.base.Engine (920, 'スレバルナ自然保護区', nan)
2022-05-02 17:46:55,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,650 INFO sqlalchemy.engine.base.Engine (921, 'ネセビルの古代都市', nan)
2022-05-02 17:46:55,650 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,651 INFO sqlalchemy.engine.base.Engine (922, 'ピリン国立公園', nan)
2022-05-02 17:46:55,651 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,651 INFO sqlalchemy.engine.base.Engine (923, 'ボヤナの教会', nan)
2022-05-02 17:46:55,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)

2022-05-02 17:46:55,652 INFO sqlalchemy.engine.base.Engine (924, 'マダラの騎馬像', nan)
2022-05-02 17:46:55,652 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,653 INFO sqlalchemy.engine.base.Engine (925, 'リラの修道院', nan)
2022-05-02 17:46:55,653 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,653 INFO sqlalchemy.engine.base.Engine (928, '胡朝の要塞', nan)
2022-05-02 17:46:55,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,655 INFO sqlalchemy.engine.base.Engine (929, '古都ホイアン', nan)
2022-05-02 17:46:55,655 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,656 INFO sqlalchemy.engine.base.Engine (930, 'ハノイにあるタン・ロン皇城遺跡の中心地', nan)
2022-05-02 17:46:55,656 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,656 INFO sqlalchemy.engine.base.Engine (931, 'ハ・ロン湾', nan)
2022-05-02 17:46:55,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,657 INFO sqlalchemy.engine.base.Engine (932, 'フエの歴史的建造物群', nan)
2022-05-02 17:46:55,657 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,658 INFO sqlalchemy.engine.base.Engine (933, 'フォン・ニャ‐ケ・バン国立公園', nan)
2022-05-02 17:46:55,658 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,658 INFO sqlalchemy.engine.base.Engine (934, 'ミーソン聖域', nan)
2022-05-02 17:46:55,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,659 INFO sqlalchemy.engine.base.Engine (935, 'チャン・アンの景観関連遺産群', nan)
2022-05-02 17:46:55,659 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,659 INFO sqlalchemy.engine.base.Engine (936, 'アボメーの王宮群', nan)
2022-05-02 17:46:55,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,660 INFO sqlalchemy.engine.base.Engine (937, 'カナイマ国立公園', nan)
2022-05-02 17:46:55,660 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,661 INFO sqlalchemy.engine.base.Engine (938, 'カラカスの大学都市', nan)
2022-05-02 17:46:55,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,661 INFO sqlalchemy.engine.base.Engine (939, 'コロとその港', nan)
2022-05-02 17:46:55,661 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,662 INFO sqlalchemy.engine.base.Engine (940, 'ネスヴィシにあるラジヴィル家の建築と邸宅および文化関連遺産群', nan)
2022-05-02 17:46:55,662 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,662 INFO sqlalchemy.engine.base.Engine (941, 'ミール城と関連遺産群', nan)
2022-05-02 17:46:55,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,663 INFO sqlalchemy.engine.base.Engine (943, 'ベリーズ・バリア・リーフ自然保護区', nan)
2022-05-02 17:46:55,663 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,663 INFO sqlalchemy.engine.base.Engine (944, 'アレキパの歴史地区', nan)
2022-05-02 17:46:55,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,664 INFO sqlalchemy.engine.base.Engine (945, 'ウアスカラン国立公園', nan)
2022-05-02 17:46:55,664 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,665 INFO sqlalchemy.engine.base.Engine (946, 'クスコの市街', nan)
2022-05-02 17:46:55,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,665 INFO sqlalchemy.engine.base.Engine (947, '聖都カラル・スペ', nan)
2022-05-02 17:46:55,665 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,666 INFO sqlalchemy.engine.base.Engine (948, 'チャビンの考古遺跡', nan)
2022-05-02 17:46:55,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,666 INFO sqlalchemy.engine.base.Engine (949, 'チャンチャンの考古地区', nan)
2022-05-02 17:46:55,666 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,667 INFO sqlalchemy.engine.base.Engine (951, 'マチュ・ピチュ', nan)
2022-05-02 17:46:55,667 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,667 INFO sqlalchemy.engine.base.Engine (952, 'マヌー国立公園', nan)
2022-05-02 17:46:55,668 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,668 INFO sqlalchemy.engine.base.Engine (953, 'リオ・アビセオ国立公園', nan)
2022-05-02 17:46:55,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,669 INFO sqlalchemy.engine.base.Engine (954, 'リマの歴史地区', nan)
2022-05-02 17:46:55,669 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,669 INFO sqlalchemy.engine.base.Engine (956, '建築家ヴィクトール・オルタによる主な邸宅（ブリュッセル）', nan)
2022-05-02 17:46:55,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,670 INFO sqlalchemy.engine.base.Engine (957, 'ストックレ邸', nan)
2022-05-02 17:46:55,670 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,671 INFO sqlalchemy.engine.base.Engine (958, 'スピエンヌにある新石器時代の火打ち石の鉱山発掘地（モンス）', nan)
2022-05-02 17:46:55,671 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,672 INFO sqlalchemy.engine.base.Engine (959, 'トゥルネーのノートル・ダム大聖堂', nan)
2022-05-02 17:46:55,672 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,672 INFO sqlalchemy.engine.base.Engine (960, 'プランタン＝モレトゥスの家屋・工房・博物館とその関連施設', nan)
2022-05-02 17:46:55,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,673 INFO sqlalchemy.engine.base.Engine (961, 'フランドル地方のベギン会の建物', nan)
2022-05-02 17:46:55,673 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,673 INFO sqlalchemy.engine.base.Engine (962, 'ブリュッセルのグラン・プラス', nan)
2022-05-02 17:46:55,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,674 INFO sqlalchemy.engine.base.Engine (963, 'ブリュージュの歴史地区', nan)
2022-05-02 17:46:55,674 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,675 INFO sqlalchemy.engine.base.Engine (964, 'ラ・ルヴィエールとル・ルー（エノー）の中央運河の4つの閘門とその周辺環境', nan)
2022-05-02 17:46:55,675 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,675 INFO sqlalchemy.engine.base.Engine (965, 'ワロン地方の主要な鉱山遺跡', nan)
2022-05-02 17:46:55,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,676 INFO sqlalchemy.engine.base.Engine (968, 'ヴィエリチカとボフニャの王立岩塩坑', nan)
2022-05-02 17:46:55,676 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,676 INFO sqlalchemy.engine.base.Engine (969, 'ヴロツワフの百周年記念ホール', nan)

2022-05-02 17:46:55,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,677 INFO sqlalchemy.engine.base.Engine (970, 'カルヴァリア・ゼブジドフスカ：マニエリスム様式の建築と公園に関連する景観と巡礼公園', nan)
2022-05-02 17:46:55,677 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,678 INFO sqlalchemy.engine.base.Engine (971, 'クラクフの歴史地区', nan)
2022-05-02 17:46:55,678 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,678 INFO sqlalchemy.engine.base.Engine (972, 'ザモシチの旧市街', nan)
2022-05-02 17:46:55,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,679 INFO sqlalchemy.engine.base.Engine (973, 'トルンの中世都市', nan)
2022-05-02 17:46:55,679 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,679 INFO sqlalchemy.engine.base.Engine (974, 'マウォポルスカ南部の木造教会群', nan)
2022-05-02 17:46:55,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,680 INFO sqlalchemy.engine.base.Engine (975, 'マルボルクのドイツ騎士修道会の城', nan)
2022-05-02 17:46:55,680 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,681 INFO sqlalchemy.engine.base.Engine (976, 'ヤヴォルとシフィドニツァの平和教会', nan)
2022-05-02 17:46:55,681 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,681 INFO sqlalchemy.engine.base.Engine (977, 'ワルシャワの歴史地区', nan)
2022-05-02 17:46:55,682 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,743 INFO sqlalchemy.engine.base.Engine (980, 'カルパティア地方のポーランドとウクライナ領にある木造教会群', nan)
2022-05-02 17:46:55,743 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,744 INFO sqlalchemy.engine.base.Engine (981, 'ヴィシェグラードのメフメド・パシャ・ソコロヴィッチ橋', nan)
2022-05-02 17:46:55,744 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,745 INFO sqlalchemy.engine.base.Engine (982, 'モスタル旧市街の石橋と周辺', nan)
2022-05-02 17:46:55,745 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,745 INFO sqlalchemy.engine.base.Engine (984, 'カルパティア山脈と他のヨーロッパ地域のブナ原生林', nan)
2022-05-02 17:46:55,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,746 INFO sqlalchemy.engine.base.Engine (985, 'ツォディロの岩絵群', nan)
2022-05-02 17:46:55,746 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,747 INFO sqlalchemy.engine.base.Engine (986, 'オカバンゴ・デルタ', nan)
2022-05-02 17:46:55,747 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,747 INFO sqlalchemy.engine.base.Engine (987, 'サマイパタの砦', nan)
2022-05-02 17:46:55,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,748 INFO sqlalchemy.engine.base.Engine (988, 'スクレの歴史都市', nan)
2022-05-02 17:46:55,748 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,749 INFO sqlalchemy.engine.base.Engine (989, 'チキトスのイエズス会ミッション', nan)
2022-05-02 17:46:55,749 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,749 INFO sqlalchemy.engine.base.Engine (990, 'ティワナク：ティワナク文化の宗教的・政治的中心地', nan)
2022-05-02 17:46:55,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,750 INFO sqlalchemy.engine.base.Engine (991, 'ノエル・ケンプ・メルカード国立公園', nan)
2022-05-02 17:46:55,750 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,751 INFO sqlalchemy.engine.base.Engine (992, 'ポトシの市街', nan)
2022-05-02 17:46:55,751 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,752 INFO sqlalchemy.engine.base.Engine (993, 'アゾレス諸島の港町アングラ・ド・エロイズモ', nan)
2022-05-02 17:46:55,753 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,753 INFO sqlalchemy.engine.base.Engine (994, 'アルコバサの修道院', nan)
2022-05-02 17:46:55,754 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,755 INFO sqlalchemy.engine.base.Engine (995, 'アルト・ドウロのワイン生産地域', nan)
2022-05-02 17:46:55,755 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,756 INFO sqlalchemy.engine.base.Engine (996, 'エヴォラの歴史地区', nan)
2022-05-02 17:46:55,756 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,756 INFO sqlalchemy.engine.base.Engine (997, 'ギマランイスの歴史地区', nan)
2022-05-02 17:46:55,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,757 INFO sqlalchemy.engine.base.Engine (998, 'シントラの文化的景観', nan)
2022-05-02 17:46:55,757 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,758 INFO sqlalchemy.engine.base.Engine (999, 'トマールのキリスト騎士団の修道院', nan)
2022-05-02 17:46:55,758 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,759 INFO sqlalchemy.engine.base.Engine (1000, 'バターリャ修道院', nan)
2022-05-02 17:46:55,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,759 INFO sqlalchemy.engine.base.Engine (1001, 'ピーコ島のブドウ栽培の景観', nan)
2022-05-02 17:46:55,760 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,760 INFO sqlalchemy.engine.base.Engine (1002, 'ポルトの歴史地区、ルイス1世橋とセラ・ド・ピラール修道院', nan)
2022-05-02 17:46:55,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,761 INFO sqlalchemy.engine.base.Engine (1003, 'マデイラ島の照葉樹林', nan)
2022-05-02 17:46:55,761 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,761 INFO sqlalchemy.engine.base.Engine (1004, 'リスボンのジェロニモス修道院とベレンの塔', nan)
2022-05-02 17:46:55,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,762 INFO sqlalchemy.engine.base.Engine (1005, '国境防衛都市エルヴァスとその要塞群', nan)
2022-05-02 17:46:55,762 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,763 INFO sqlalchemy.engine.base.Engine (1006, 'コインブラ大学：アルタとソフィア', nan)
2022-05-02 17:46:55,763 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,763 INFO sqlalchemy.engine.base.Engine (1009, 'コパンのマヤ遺跡', nan)
2022-05-02 17:46:55,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,764 INFO sqlalchemy.engine.base.Engine (1010, 'リオ・プラタノ生物圏保存地域', nan)
2022-05-02 17:46:55,764 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,765 INFO sqlalchemy.engine.base.Engine (1011, 'ビキニ環礁－核実験場となった海', nan)
2022-05-02 17:46:55,765 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,765 INFO sqlalchemy.engine.base.Engine (1012, 'アツィナナナの熱帯雨林', nan)

2022-05-02 17:46:55,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,766 INFO sqlalchemy.engine.base.Engine (1013, 'アンブヒマンガの丘の王領地', nan)
2022-05-02 17:46:55,766 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,767 INFO sqlalchemy.engine.base.Engine (1017, 'アスキア墳墓', nan)
2022-05-02 17:46:55,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,767 INFO sqlalchemy.engine.base.Engine (1021, 'ハル・サフリエニの地下墳墓', nan)
2022-05-02 17:46:55,767 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,768 INFO sqlalchemy.engine.base.Engine (1022, 'バレッタの市街', nan)
2022-05-02 17:46:55,768 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,769 INFO sqlalchemy.engine.base.Engine (1023, 'マルタの巨石神殿群', nan)
2022-05-02 17:46:55,769 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,769 INFO sqlalchemy.engine.base.Engine (1024, 'キナバル自然公園', nan)
2022-05-02 17:46:55,770 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,770 INFO sqlalchemy.engine.base.Engine (1025, 'グヌン・ムル国立公園', nan)
2022-05-02 17:46:55,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,771 INFO sqlalchemy.engine.base.Engine (1026, 'メラカとジョージ・タウン：マラッカ海峡の歴史都市', nan)
2022-05-02 17:46:55,771 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,772 INFO sqlalchemy.engine.base.Engine (1027, 'レンゴン渓谷の考古遺跡', nan)
2022-05-02 17:46:55,772 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,772 INFO sqlalchemy.engine.base.Engine (1039, 'ピュー族の古代都市群', nan)
2022-05-02 17:46:55,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,773 INFO sqlalchemy.engine.base.Engine (1041, 'ウシュマルの古代都市', nan)
2022-05-02 17:46:55,773 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,774 INFO sqlalchemy.engine.base.Engine (1042, 'エル・タヒンの古代都市', nan)
2022-05-02 17:46:55,774 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,774 INFO sqlalchemy.engine.base.Engine (1043, 'エル・ビスカイノ鯨保護区', nan)
2022-05-02 17:46:55,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,775 INFO sqlalchemy.engine.base.Engine (1044, 'オアハカの中部渓谷にあるヤグルとミトラの先史洞窟', nan)
2022-05-02 17:46:55,775 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,776 INFO sqlalchemy.engine.base.Engine (1045, 'オアハカの歴史地区とモンテ・アルバンの考古遺跡', nan)
2022-05-02 17:46:55,776 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,776 INFO sqlalchemy.engine.base.Engine (1046, 'オオカバマダラ蝶生物圏保存地域', nan)
2022-05-02 17:46:55,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,777 INFO sqlalchemy.engine.base.Engine (1047, 'カミノ・レアル・デ・ティエラ・アデントロ－メキシコ内陸部の王の道', nan)
2022-05-02 17:46:55,777 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,778 INFO sqlalchemy.engine.base.Engine (1048, 'カリフォルニア湾の島々と自然保護区群', nan)
2022-05-02 17:46:55,778 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,778 INFO sqlalchemy.engine.base.Engine (1049, 'カンペチェ州カラクムルの古代マヤ都市と保護熱帯雨林群', nan)
2022-05-02 17:46:55,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,779 INFO sqlalchemy.engine.base.Engine (1050, 'グアダラハラの救貧施設', nan)
2022-05-02 17:46:55,779 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,780 INFO sqlalchemy.engine.base.Engine (1051, 'グアナフアトの歴史地区と鉱山', nan)
2022-05-02 17:46:55,780 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,780 INFO sqlalchemy.engine.base.Engine (1052, 'ケレタロ州シエラ・ゴルダのフランシスコ会ミッション', nan)
2022-05-02 17:46:55,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,781 INFO sqlalchemy.engine.base.Engine (1053, 'ケレタロの歴史的建造物地区', nan)
2022-05-02 17:46:55,781 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,781 INFO sqlalchemy.engine.base.Engine (1054, 'サカテカスの歴史地区', nan)
2022-05-02 17:46:55,782 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,782 INFO sqlalchemy.engine.base.Engine (1055, 'サンフランシスコ山地の洞窟壁画', nan)
2022-05-02 17:46:55,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,783 INFO sqlalchemy.engine.base.Engine (1056, 'サン・ミゲルの要塞都市とアトトニルコにあるナザレのイエスの聖地', nan)
2022-05-02 17:46:55,783 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,783 INFO sqlalchemy.engine.base.Engine (1057, 'シアン・カーン自然保護区', nan)
2022-05-02 17:46:55,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,784 INFO sqlalchemy.engine.base.Engine (1058, 'ソチカルコの古代遺跡地帯', nan)
2022-05-02 17:46:55,784 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,785 INFO sqlalchemy.engine.base.Engine (1059, 'チチェン・イツァの古代都市', nan)
2022-05-02 17:46:55,786 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,786 INFO sqlalchemy.engine.base.Engine (1061, 'トラコタルパンの歴史的建造物地区', nan)
2022-05-02 17:46:55,787 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,787 INFO sqlalchemy.engine.base.Engine (1062, 'パキメの遺跡', nan)
2022-05-02 17:46:55,788 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,789 INFO sqlalchemy.engine.base.Engine (1063, 'パレンケの古代都市と国立公園', nan)
2022-05-02 17:46:55,789 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,789 INFO sqlalchemy.engine.base.Engine (1064, 'プエブラの歴史地区', nan)
2022-05-02 17:46:55,790 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,790 INFO sqlalchemy.engine.base.Engine (1065, 'ポポカテペトル山麓の16世紀初期の修道院群', nan)
2022-05-02 17:46:55,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,791 INFO sqlalchemy.engine.base.Engine (1066, 'メキシコ国立自治大学（UNAM）の中央大学都市キャンパス', nan)
2022-05-02 17:46:55,791 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,792 INFO sqlalchemy.engine.base.Engine (1067, 'メキシコ・シティの歴史地区とソチミルコ', nan)
2022-05-02 17:46:55,792 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,792 INFO sqlalchemy.engine.base.Engine (1068, 'モレリアの歴史地区', nan)
2022-05-02 17:46:55,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,793 INFO sqlalchemy.engine.base.Engine (1069, '歴史的要塞都市カンペチェ', nan)

2022-05-02 17:46:55,793 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,794 INFO sqlalchemy.engine.base.Engine (1070, 'リュウゼツランの景観とテキーラ村の古式産業施設群', nan)
2022-05-02 17:46:55,794 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,794 INFO sqlalchemy.engine.base.Engine (1071, 'ルイス・バラガン邸と仕事場', nan)
2022-05-02 17:46:55,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,795 INFO sqlalchemy.engine.base.Engine (1072, 'エル・ピナカーテとグラン・デシエルト・デ・アルタル生物圏保存地域', nan)
2022-05-02 17:46:55,795 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,796 INFO sqlalchemy.engine.base.Engine (1073, 'パドレ・テンブレケ水利施設の水道橋', nan)
2022-05-02 17:46:55,796 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,796 INFO sqlalchemy.engine.base.Engine (1076, 'アープラヴァシ・ガート', nan)
2022-05-02 17:46:55,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,797 INFO sqlalchemy.engine.base.Engine (1081, 'ヴォルビリスの考古遺跡', nan)
2022-05-02 17:46:55,797 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,798 INFO sqlalchemy.engine.base.Engine (1082, 'エッサウィーラ（旧名モガドール）の旧市街', nan)
2022-05-02 17:46:55,798 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,798 INFO sqlalchemy.engine.base.Engine (1090, 'オルホン渓谷の文化的景観', nan)
2022-05-02 17:46:55,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,799 INFO sqlalchemy.engine.base.Engine (1091, 'モンゴルのアルタイ山脈にある岩面画群', nan)
2022-05-02 17:46:55,799 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,799 INFO sqlalchemy.engine.base.Engine (1092, 'ウヴス・ヌール盆地', nan)
2022-05-02 17:46:55,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,800 INFO sqlalchemy.engine.base.Engine (1094, 'グレート・ブルカン・カルドゥン山と周辺の聖なる景観', nan)
2022-05-02 17:46:55,800 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,801 INFO sqlalchemy.engine.base.Engine (1095, 'コトルの文化歴史地域と自然', nan)
2022-05-02 17:46:55,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,802 INFO sqlalchemy.engine.base.Engine (1096, 'ドゥルミトル国立公園', nan)
2022-05-02 17:46:55,802 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,803 INFO sqlalchemy.engine.base.Engine (1097, 'ウンム・アッラサス（カストロム・メファア）', nan)
2022-05-02 17:46:55,803 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,804 INFO sqlalchemy.engine.base.Engine (1098, '砂漠の城クセイル・アムラ', nan)
2022-05-02 17:46:55,804 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,804 INFO sqlalchemy.engine.base.Engine (1099, '隊商都市ペトラ', nan)
2022-05-02 17:46:55,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,805 INFO sqlalchemy.engine.base.Engine (1100, 'ワディ・ラム保護地域', nan)
2022-05-02 17:46:55,805 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,805 INFO sqlalchemy.engine.base.Engine (1101, 'イエス洗礼の地「ヨルダン川対岸のベタニア」（アル・マグタス)', nan)
2022-05-02 17:46:55,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,806 INFO sqlalchemy.engine.base.Engine (1103, '古都ルアン・パバン', nan)
2022-05-02 17:46:55,806 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,807 INFO sqlalchemy.engine.base.Engine (1104, 'チャムパーサックの文化的景観にあるワット・プーと関連古代遺跡群', nan)
2022-05-02 17:46:55,807 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,808 INFO sqlalchemy.engine.base.Engine (1106, 'リガの歴史地区', nan)
2022-05-02 17:46:55,808 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,808 INFO sqlalchemy.engine.base.Engine (1107, 'ケルナヴェ古代遺跡（ケルナヴェ文化保護区）', nan)
2022-05-02 17:46:55,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,809 INFO sqlalchemy.engine.base.Engine (1108, 'ビリニュスの歴史地区', nan)
2022-05-02 17:46:55,809 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,810 INFO sqlalchemy.engine.base.Engine (1109, 'クルスキー砂洲', nan)
2022-05-02 17:46:55,810 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,810 INFO sqlalchemy.engine.base.Engine (1110, 'ガダーミスの旧市街', nan)
2022-05-02 17:46:55,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,811 INFO sqlalchemy.engine.base.Engine (1111, 'キレーネの考古遺跡', nan)
2022-05-02 17:46:55,811 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,812 INFO sqlalchemy.engine.base.Engine (1112, 'サブラータの考古遺跡', nan)
2022-05-02 17:46:55,812 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,813 INFO sqlalchemy.engine.base.Engine (1113, 'タドラールト・アカークスの岩絵遺跡群', nan)
2022-05-02 17:46:55,813 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,813 INFO sqlalchemy.engine.base.Engine (1115, 'オラシュティエ山脈のダキア人要塞', nan)
2022-05-02 17:46:55,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,814 INFO sqlalchemy.engine.base.Engine (1116, 'シギショアラの歴史地区', nan)
2022-05-02 17:46:55,814 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,815 INFO sqlalchemy.engine.base.Engine (1117, 'ドナウ・デルタ', nan)
2022-05-02 17:46:55,815 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,815 INFO sqlalchemy.engine.base.Engine (1118, 'ホレズの修道院', nan)
2022-05-02 17:46:55,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,816 INFO sqlalchemy.engine.base.Engine (1119, 'マラムレシュの木造教会群', nan)
2022-05-02 17:46:55,816 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,816 INFO sqlalchemy.engine.base.Engine (1120, 'モルドヴァ地方の教会群', nan)
2022-05-02 17:46:55,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,817 INFO sqlalchemy.engine.base.Engine (1121, '要塞教会のあるトランシルヴァニアの村落', nan)
2022-05-02 17:46:55,817 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,818 INFO sqlalchemy.engine.base.Engine (1123, 'ルクセンブルク市の旧市街と要塞', nan)
2022-05-02 17:46:55,819 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,820 INFO sqlalchemy.engine.base.Engine (1124, 'アンジャル', nan)
2022-05-02 17:46:55,820 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,821 INFO sqlalchemy.engine.base.Engine (1125, 'カディーシャ渓谷（聖なる谷）と神の杉の森（ホルシュ・アルツ・エルラブ）', nan)

2022-05-02 17:46:55,823 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,823 INFO sqlalchemy.engine.base.Engine (1126, 'バアルベック', nan)
2022-05-02 17:46:55,824 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,824 INFO sqlalchemy.engine.base.Engine (1127, 'フェニキア都市ティルス', nan)
2022-05-02 17:46:55,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,825 INFO sqlalchemy.engine.base.Engine (1128, 'フェニキア都市ビブロス', nan)
2022-05-02 17:46:55,825 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,826 INFO sqlalchemy.engine.base.Engine (1129, 'アルタイ・ゴールデン・マウンテン', nan)
2022-05-02 17:46:55,827 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,827 INFO sqlalchemy.engine.base.Engine (1130, 'ウラジーミルとスーズダリの白い建造物群', nan)
2022-05-02 17:46:55,828 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,828 INFO sqlalchemy.engine.base.Engine (1131, 'ウランゲリ島保護区の自然生態系', nan)
2022-05-02 17:46:55,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,829 INFO sqlalchemy.engine.base.Engine (1132, 'カザン・クレムリンの歴史的関連建造物群', nan)
2022-05-02 17:46:55,829 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,830 INFO sqlalchemy.engine.base.Engine (1133, 'カムチャツカ火山群', nan)
2022-05-02 17:46:55,830 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,831 INFO sqlalchemy.engine.base.Engine (1134, 'キージ島の木造教会と集落', nan)
2022-05-02 17:46:55,831 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,831 INFO sqlalchemy.engine.base.Engine (1135, 'コミの原生林', nan)
2022-05-02 17:46:55,832 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,832 INFO sqlalchemy.engine.base.Engine (1136, 'コローメンスコエ：昇天教会（ヴォズネセーニエ教会）', nan)
2022-05-02 17:46:55,833 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,834 INFO sqlalchemy.engine.base.Engine (1137, 'サンクト・ペテルブルクの歴史地区と関連建造物群', nan)
2022-05-02 17:46:55,834 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,834 INFO sqlalchemy.engine.base.Engine (1138, 'シホテ・アリニ山脈中央部', nan)
2022-05-02 17:46:55,835 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,835 INFO sqlalchemy.engine.base.Engine (1139, 'セルギエフ・ポサドのトロイツェ・セルギエフ大修道院', nan)
2022-05-02 17:46:55,836 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,836 INFO sqlalchemy.engine.base.Engine (1140, 'ソロヴェツキー諸島の文化歴史的建造物群', nan)
2022-05-02 17:46:55,837 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,837 INFO sqlalchemy.engine.base.Engine (1141, 'デルベントのシタデル、古代都市、要塞建築物群', nan)
2022-05-02 17:46:55,838 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,838 INFO sqlalchemy.engine.base.Engine (1142, '西カフカス山脈', nan)
2022-05-02 17:46:55,839 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,839 INFO sqlalchemy.engine.base.Engine (1143, 'ノヴォデーヴィチー修道院関連遺産群', nan)
2022-05-02 17:46:55,840 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,841 INFO sqlalchemy.engine.base.Engine (1144, 'ノヴゴロドと周辺の歴史的建造物群', nan)
2022-05-02 17:46:55,841 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,870 INFO sqlalchemy.engine.base.Engine (1145, 'バイカル湖', nan)
2022-05-02 17:46:55,871 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,872 INFO sqlalchemy.engine.base.Engine (1146, 'フェラポントフ修道院関連遺産群', nan)
2022-05-02 17:46:55,873 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,874 INFO sqlalchemy.engine.base.Engine (1147, 'プトラナ台地', nan)
2022-05-02 17:46:55,875 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,875 INFO sqlalchemy.engine.base.Engine (1149, 'ヤロスラーヴリの歴史地区', nan)
2022-05-02 17:46:55,876 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,876 INFO sqlalchemy.engine.base.Engine (1150, 'レナ石柱自然公園', nan)
2022-05-02 17:46:55,877 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:55,878 INFO sqlalchemy.engine.base.Engine (1151, 'ボルガルの歴史的考古学的遺産群', nan)
2022-05-02 17:46:55,884 INFO sqlalchemy.engine.base.Engine COMMIT

# ■ CRUD操作（Create/Read/Update/Delete）

## Read

In [13]:
db = db_session.query(WH).all()

2022-05-02 17:46:55,897 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2022-05-02 17:46:55,897 INFO sqlalchemy.engine.base.Engine SELECT "WH_class".id AS "WH_class_id", "WH_class"."WH_num" AS "WH_class_WH_num", "WH_class"."WH_name" AS "WH_class_WH_name", "WH_class".text AS "WH_class_text"
FROM "WH_class"
2022-05-02 17:46:55,898 INFO sqlalchemy.engine.base.Engine ()

In [14]:
for row in db:
    print(row.id)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981

In [15]:
#特定のカラムを抽出
db = db_session.query(WH.id, WH.WH_name).all()

2022-05-02 17:46:56,005 INFO sqlalchemy.engine.base.Engine SELECT "WH_class".id AS "WH_class_id", "WH_class"."WH_name" AS "WH_class_WH_name"
FROM "WH_class"
2022-05-02 17:46:56,006 INFO sqlalchemy.engine.base.Engine ()

In [16]:
#条件抽出
db = db_session.query(WH).filter(WH.WH_num > 1000).all()

2022-05-02 17:46:56,032 INFO sqlalchemy.engine.base.Engine SELECT "WH_class".id AS "WH_class_id", "WH_class"."WH_num" AS "WH_class_WH_num", "WH_class"."WH_name" AS "WH_class_WH_name", "WH_class".text AS "WH_class_text"
FROM "WH_class"
WHERE "WH_class"."WH_num" > ?
2022-05-02 17:46:56,032 INFO sqlalchemy.engine.base.Engine (1000,)

In [17]:
#取得レコード数の制限
#db = db_session.query(WH).limit(20).all()

In [18]:
#レコード数の並べ替え
from sqlalchemy import desc

db = db_session.query(WH).order_by(desc(WH.WH_num)).limit(20).all()

2022-05-02 17:46:56,144 INFO sqlalchemy.engine.base.Engine SELECT "WH_class".id AS "WH_class_id", "WH_class"."WH_num" AS "WH_class_WH_num", "WH_class"."WH_name" AS "WH_class_WH_name", "WH_class".text AS "WH_class_text"
FROM "WH_class" ORDER BY "WH_class"."WH_num" DESC
 LIMIT ? OFFSET ?
2022-05-02 17:46:56,144 INFO sqlalchemy.engine.base.Engine (20, 0)

In [19]:
for row in db:
    print(row.WH_num)

1151
1150
1149
1147
1146
1145
1144
1143
1142
1141
1140
1139
1138
1137
1136
1135
1134
1133
1132
1131

## Create

In [20]:
wh = WH(WH_num=10000, WH_name=None, text=None)

In [21]:
db_session.add(wh)
db_session.commit()

2022-05-02 17:46:57,759 INFO sqlalchemy.engine.base.Engine INSERT INTO "WH_class" ("WH_num", "WH_name", text) VALUES (?, ?, ?)
2022-05-02 17:46:57,761 INFO sqlalchemy.engine.base.Engine (10000, None, None)
2022-05-02 17:46:57,764 INFO sqlalchemy.engine.base.Engine COMMIT

In [22]:
db = db_session.query(WH).filter(WH.WH_num >= 10000).all()

2022-05-02 17:46:58,255 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2022-05-02 17:46:58,256 INFO sqlalchemy.engine.base.Engine SELECT "WH_class".id AS "WH_class_id", "WH_class"."WH_num" AS "WH_class_WH_num", "WH_class"."WH_name" AS "WH_class_WH_name", "WH_class".text AS "WH_class_text"
FROM "WH_class"
WHERE "WH_class"."WH_num" >= ?
2022-05-02 17:46:58,257 INFO sqlalchemy.engine.base.Engine (10000,)

In [25]:
for row in db:
    print(row.WH_name)

None